package proposallineage

import (
	"strings"

	"github.com/git-town/git-town/v23/internal/config/configdomain"
	"github.com/git-town/git-town/v23/internal/forge/forgedomain"
	"github.com/git-town/git-town/v23/internal/git/gitdomain"
	. "github.com/git-town/git-town/v23/pkg/prelude"
)

func RenderForest(forest ForestWithProposals, currentBranch gitdomain.LocalBranchName, direction configdomain.ProposalBreadcrumbDirection, connector Option[forgedomain.Connector]) string {
	var builder strings.Builder
	builder.WriteString("\n-------------------------\n")

	for _, tree := range forest {
		AppendTree(&builder, tree, currentBranch, direction, connector)
	}

	builder.WriteString("\n<sup>[Stack](https://www.git-town.com/how-to/proposal-breadcrumb.html) generated by [Git Town](https://github.com/git-town/git-town)</sup>\n")
	return builder.String()
}
