package proposallineage

import (
	"slices"
	"strings"

	"github.com/git-town/git-town/v22/internal/config/configdomain"
	"github.com/git-town/git-town/v22/internal/git/gitdomain"
	"github.com/git-town/git-town/v22/internal/gohacks/stringslice"
)

const spacesPerIndent = 2

func RenderTree(tree TreeNodeWithProposal, currentBranch gitdomain.LocalBranchName, direction configdomain.ProposalBreadcrumbDirection, style configdomain.ProposalBreadcrumbStyle) string {
	builder := stringslice.NewCollector()

	flat := style == configdomain.ProposalBreadcrumbStyleAuto && tree.IsLinear()

	switch direction {
	case configdomain.ProposalBreadcrumbDirectionDown:
		renderNodeDown(&builder, tree, currentBranch, 0, false, flat)
	case configdomain.ProposalBreadcrumbDirectionUp:
		maxDepth := tree.MaxDepth()
		renderNodeUp(&builder, tree, currentBranch, maxDepth, flat)
	}

	result := strings.Builder{}
	result.WriteString("\n-------------------------")
	result.WriteString(strings.Join(builder.Result(), "\n"))
	result.WriteString("\n<sup>[Stack](https://www.git-town.com/how-to/proposal-breadcrumb.html) generated by [Git Town](https://github.com/git-town/git-town)</sup>\n")
	return strings.Join(builder.Result(), "\n")
}

func renderNodeDown(lines *stringslice.Collector, node TreeNodeWithProposal, currentBranch gitdomain.LocalBranchName, depth int, foundCurrent bool, flat bool) {
	if node.BranchOrAncestorHasProposal() || !foundCurrent {
		indent := 0
		if !flat {
			indent = depth * spacesPerIndent
		}
		builder := strings.Builder{}
		builder.WriteString(strings.Repeat(" ", indent))
		builder.WriteString("- ")
		if proposal, hasProposal := node.Proposal.Get(); hasProposal {
			builder.WriteString(proposal.Data.Data().URL)
		} else {
			builder.WriteString(node.Branch.String())
		}
		isCurrentBranch := node.Branch == currentBranch && !foundCurrent
		if isCurrentBranch {
			builder.WriteString(" :point_left:")
			foundCurrent = true
		}
		lines.Add(builder.String())
	}
	for _, child := range node.Children {
		renderNodeDown(lines, child, currentBranch, depth+1, foundCurrent, flat)
	}
}

func renderNodeUp(lines *stringslice.Collector, node TreeNodeWithProposal, currentBranch gitdomain.LocalBranchName, maxDepth int, flat bool) bool {
	renderNodeDown(lines, node, currentBranch, maxDepth, false, flat)
	slices.Reverse(lines)
}
