package proposallineage

import (
	"strings"

	"github.com/git-town/git-town/v23/internal/config/configdomain"
	"github.com/git-town/git-town/v23/internal/forge/forgedomain"
	"github.com/git-town/git-town/v23/internal/git/gitdomain"
	. "github.com/git-town/git-town/v23/pkg/prelude"
)

const (
	// spacesPerIndentDefault is the nested-list indentation for forges whose
	// Markdown follows CommonMark/GFM (GitHub, GitLab, Gitea, Forgejo), which
	// nest a list level at 2 spaces.
	spacesPerIndentDefault = 2
	// spacesPerIndentBitbucket is the nested-list indentation for Bitbucket Cloud,
	// whose Python-Markdown renderer needs 4 spaces to nest a list level. With 2
	// spaces it collapses every two stack levels into one (github.com/Python-Markdown/markdown/issues/451).
	spacesPerIndentBitbucket = 4
)

func RenderTree(tree TreeNodeWithProposal, currentBranch gitdomain.LocalBranchName, direction configdomain.ProposalBreadcrumbDirection, forgeTypeOpt Option[forgedomain.ForgeType], connector Option[forgedomain.Connector]) string {
	var builder strings.Builder
	builder.WriteString("\n-------------------------\n")

	forgeType, hasForgeType := forgeTypeOpt.Get()
	spacesPerIndent := spacesPerIndentDefault
	if hasForgeType && forgeType == forgedomain.ForgeTypeBitbucket {
		spacesPerIndent = spacesPerIndentBitbucket
	}

	switch direction {
	case configdomain.ProposalBreadcrumbDirectionDown:
		renderNodeDown(&builder, tree, currentBranch, 0, false, connector, spacesPerIndent)
	case configdomain.ProposalBreadcrumbDirectionUp:
		renderNodeUp(&builder, tree, currentBranch, connector)
	}

	// Bitbucket Cloud's Python-Markdown escapes raw HTML, so a <sup> footer renders
	// as literal "<sup>...</sup>" text. Emit italic Markdown there instead; every
	// other forge keeps the original superscript footer.
	if hasForgeType && forgeType == forgedomain.ForgeTypeBitbucket {
		builder.WriteString("\n*[Stack](https://www.git-town.com/how-to/proposal-breadcrumb.html) generated by [Git Town](https://github.com/git-town/git-town)*\n")
	} else {
		builder.WriteString("\n<sup>[Stack](https://www.git-town.com/how-to/proposal-breadcrumb.html) generated by [Git Town](https://github.com/git-town/git-town)</sup>\n")
	}
	return builder.String()
}

func renderNodeDown(builder *strings.Builder, node TreeNodeWithProposal, currentBranch gitdomain.LocalBranchName, depth int, foundCurrent bool, connector Option[forgedomain.Connector], spacesPerIndent int) {
	if node.BranchOrAncestorHasProposal() || !foundCurrent {
		indent := depth * spacesPerIndent
		builder.WriteString(strings.Repeat(" ", indent))
		builder.WriteString("- ")
		isCurrentBranch := node.Branch == currentBranch && !foundCurrent
		proposal, hasProposal := node.Proposal.Get()
		switch {
		case isCurrentBranch && hasProposal:
			builder.WriteString("**")
			builder.WriteString(proposal.Data.Data().Title.String())
			builder.WriteString("**")
		case hasProposal:
			builder.WriteString(proposalReference(proposal, connector))
		case isCurrentBranch:
			builder.WriteString("**")
			builder.WriteString(node.Branch.String())
			builder.WriteString("**")
		default:
			builder.WriteString(node.Branch.String())
		}
		if isCurrentBranch {
			builder.WriteString(" :point_left:")
			foundCurrent = true
		}
		builder.WriteString("\n")
	}
	for _, child := range node.Children {
		renderNodeDown(builder, child, currentBranch, depth+1, foundCurrent, connector, spacesPerIndent)
	}
}

func renderNodeUp(builder *strings.Builder, node TreeNodeWithProposal, currentBranch gitdomain.LocalBranchName, connector Option[forgedomain.Connector]) bool {
	// First render children (they appear at top in up direction)
	// foundCurrent propagates UP from children to parents
	childFoundCurrent := false
	for _, child := range node.Children {
		if renderNodeUp(builder, child, currentBranch, connector) {
			childFoundCurrent = true
		}
	}
	isCurrentBranch := node.Branch == currentBranch
	// In up direction: if childFoundCurrent or isCurrentBranch, we're on the path from current to root
	onPathToRoot := childFoundCurrent || isCurrentBranch
	// Render if: has proposal/descendant with proposal, OR on path from current to root
	if node.BranchOrAncestorHasProposal() || onPathToRoot {
		builder.WriteString("- ")
		proposal, hasProposal := node.Proposal.Get()
		switch {
		case isCurrentBranch:
			builder.WriteString("**")
			builder.WriteString(node.Branch.String())
			builder.WriteString("**")
		case hasProposal:
			builder.WriteString(proposalReference(proposal, connector))
		default:
			builder.WriteString(node.Branch.String())
		}
		if isCurrentBranch {
			builder.WriteString(" :point_left:")
		}
		builder.WriteString("\n")
	}
	return onPathToRoot
}

func proposalReference(proposal forgedomain.Proposal, connector Option[forgedomain.Connector]) string {
	proposalData := proposal.Data.Data()
	if proposalConnector, hasConnector := connector.Get(); hasConnector {
		if renderedReference := proposalConnector.ProposalReference(proposalData); renderedReference != "" {
			return renderedReference
		}
	}
	return forgedomain.ProposalReferenceFallback(proposalData)
}
