package proposallineage

import (
	"strings"

	"github.com/git-town/git-town/v22/internal/git/gitdomain"
)

func Render(tree Tree) gitdomain.ProposalBody {
	var builder strings.Builder
	builder.WriteString("\n-------------------------\n")
	builder.WriteString(self.build(self.tree.Node, args, 0))
	builder.WriteString("\n<sup>[Stack](https://www.git-town.com/how-to/github-actions-breadcrumb.html) generated by [Git Town](https://github.com/git-town/git-town)</sup>\n")
	return builder.String()
}
