package proposallineage

import (
	"strings"

	"github.com/git-town/git-town/v22/internal/config/configdomain"
	"github.com/git-town/git-town/v22/internal/git/gitdomain"
)

const spacesPerIndent = 2

func RenderTree(tree TreeNodeWithProposal, currentBranch gitdomain.LocalBranchName, direction configdomain.ProposalBreadcrumbDirection) string {
	var builder strings.Builder
	builder.WriteString("\n-------------------------\n")

	switch direction {
	case configdomain.ProposalBreadcrumbDirectionDown:
		renderNodeDown(&builder, tree, currentBranch, 0, false)
	case configdomain.ProposalBreadcrumbDirectionUp:
		renderNodeUp(&builder, tree, currentBranch)
	}

	builder.WriteString("\n<sup>[Stack](https://www.git-town.com/how-to/proposal-breadcrumb.html) generated by [Git Town](https://github.com/git-town/git-town)</sup>\n")
	return builder.String()
}

func renderNodeDown(builder *strings.Builder, node TreeNodeWithProposal, currentBranch gitdomain.LocalBranchName, depth int, foundCurrent bool) {
	if node.BranchOrAncestorHasProposal() || !foundCurrent {
		indent := depth * spacesPerIndent
		builder.WriteString(strings.Repeat(" ", indent))
		builder.WriteString("- ")
		if proposal, hasProposal := node.Proposal.Get(); hasProposal {
			builder.WriteString(proposal.Data.Data().URL)
		} else {
			builder.WriteString(node.Branch.String())
		}
		isCurrentBranch := node.Branch == currentBranch && !foundCurrent
		if isCurrentBranch {
			builder.WriteString(" :point_left:")
			foundCurrent = true
		}
		builder.WriteString("\n")
	}
	for _, child := range node.Children {
		renderNodeDown(builder, child, currentBranch, depth+1, foundCurrent)
	}
}

func renderNodeUp(builder *strings.Builder, node TreeNodeWithProposal, currentBranch gitdomain.LocalBranchName) bool {
	// First render children (they appear at top in up direction)
	// foundCurrent propagates UP from children to parents
	childFoundCurrent := false
	for _, child := range node.Children {
		if renderNodeUp(builder, child, currentBranch) {
			childFoundCurrent = true
		}
	}
	isCurrentBranch := node.Branch == currentBranch
	// In up direction: if childFoundCurrent or isCurrentBranch, we're on the path from current to root
	onPathToRoot := childFoundCurrent || isCurrentBranch
	// Render if: has proposal/descendant with proposal, OR on path from current to root
	if node.BranchOrAncestorHasProposal() || onPathToRoot {
		builder.WriteString("- ")
		if proposal, hasProposal := node.Proposal.Get(); hasProposal {
			builder.WriteString(proposal.Data.Data().URL)
		} else {
			builder.WriteString(node.Branch.String())
		}
		if isCurrentBranch {
			builder.WriteString(" :point_left:")
		}
		builder.WriteString("\n")
	}
	return onPathToRoot
}
