#!/bin/bash

# Completely deletes all content in the test repository

source spec/helpers/repo_management.sh

echo "Entering the remote repo"
cd /tmp/git_town_specs
git remote prune origin

remove_all_remote_branches
remove_all_local_branches
remove_all_local_files

echo "Returning to the previous directory"
cd -
