# Configuration for probot-stale - https://github.com/probot/stale

# Number of days of inactivity before an Issue or Pull Request becomes stale
daysUntilStale: 7

# Number of days of inactivity before an Issue or Pull Request with the stale label is closed.
# Set to false to disable. If disabled, issues still need to be closed manually, but will remain marked as stale.
daysUntilClose: false

exemptLabels:
  - documentation
  - idea
  - feature
  - help wanted
  - improvement
  - refactoring
  
# Comment to post when marking as stale. Set to `false` to disable
pulls:
  daysUntilStale: 7
  markComment: >
    This pull request is losing momentum.
    Please help resolve it.

issues:
  daysUntilStale: 14
  markComment: >
    This issue is losing momentum.
    Please help resolve it.
