push-new-branches = false
ship-strategy = "fast-forward"
sync-upstream = true

[branches]
main = "main"
perennials = ["public"]

[ship]
delete-tracking-branch = false

[sync]
push-hook = true

[sync-strategy]
feature-branches = "merge"
perennial-branches = "rebase"
