[branches]
main = "main"
perennials = ["public"]

[ship]
delete-tracking-branch = false
strategy = "fast-forward"

[sync]
feature-strategy = "merge"
push-hook = true
upstream = true

[sync-strategy]
perennial-branches = "rebase"
