[branches]
main = "main"
perennials = ["public"]

[ship]
delete-tracking-branch = false
strategy = "fast-forward"

[sync]
feature-strategy = "merge"
perennial-strategy = "rebase"
push-hook = true
upstream = true
