push-hook = true
push-new-branches = false
ship-strategy = "fast-forward"
ship-delete-tracking-branch = false
sync-upstream = true

[branches]
main = "main"
perennials = ["public"]

[sync-strategy]
feature-branches = "merge"
perennial-branches = "rebase"
