[branches]
main = "main"
perennials = ["public"]

[ship]
delete-tracking-branch = false
strategy = "fast-forward"

[sync]
push-hook = true
upstream = true

[sync-strategy]
feature-branches = "merge"
perennial-branches = "rebase"
