archives:
  - files:
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{- .ProjectName }}_
      {{- if eq .Os "darwin" }}macos
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}intel_64
      {{- else if eq .Arch "arm64" }}arm_64
      {{- else }}{{ .Arch }}{{ end }}

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/git-town/git-town/v10/src/cmd.version={{.Env.VERSION}} -X
        github.com/git-town/git-town/v10/src/cmd.buildDate={{.Env.TODAY}}
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - linux
      - windows

changelog:
  skip: true

checksum:
  name_template: "checksums.txt"

nfpms:
  - id: git-town
    package_name: git-town
    file_name_template: >-
      {{- .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}intel_64
      {{- else if eq .Arch "arm64" }}arm_64
      {{- else }}{{ .Arch }}{{ end }}
    vendor: the Git Town authors
    maintainer: the Git Town authors
    homepage: https://www.git-town.com
    description: High-level command-line interface for Git
    license: MIT
    formats:
      - deb
      - rpm
    dependencies:
      - git

release:
  disable: true
