Style/EmptyLines:
  Enabled: false


Style/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines


Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses


Style/StringLiterals:
  EnforcedStyle: single_quotes


Metrics/AbcSize:
  Max: 19


Metrics/CyclomaticComplexity:
  Max: 7


Metrics/LineLength:
  Max: 120


Metrics/ParameterLists:
  Max: 6
