Metrics/AbcSize:
  Max: 19


Metrics/CyclomaticComplexity:
  Max: 7


Metrics/LineLength:
  Enabled: false


Metrics/ParameterLists:
  Max: 6


Style/DotPosition:
  EnforcedStyle: leading
  Enabled: true


Style/EmptyLines:
  Enabled: false


Style/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines


Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses


Style/StringLiterals:
  EnforcedStyle: single_quotes
