Style/EmptyLines:
  Enabled: false


Style/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines


Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses


Metrics/LineLength:
  Max: 120


Metrics/ParameterLists:
  Max: 6
