# frozen_string_literal: true

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - "/**/node_modules/**/*"

  DisplayCopNames: true

  DisplayStyleGuide: true

Layout/DotPosition:
  EnforcedStyle: leading
  Enabled: true

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Layout/EmptyLineBetweenDefs:
  NumberOfEmptyLines: [1, 2]

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/AbcSize:
  Max: 19

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/LineLength:
  Enabled: false

Metrics/ParameterLists:
  Max: 6

Style/EmptyCaseCondition:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

Style/NestedParenthesizedCalls:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_fail

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/TernaryParentheses:
  Enabled: false
