# frozen_string_literal: true
AllCops:
  TargetRubyVersion: 2.3

  DisplayCopNames: true

  DisplayStyleGuide: true


Metrics/AbcSize:
  Max: 19


Metrics/CyclomaticComplexity:
  Max: 7


Metrics/LineLength:
  Enabled: false


Metrics/ParameterLists:
  Max: 6


Style/DotPosition:
  EnforcedStyle: leading
  Enabled: true


Style/EmptyCaseCondition:
  Enabled: false


Style/EmptyLines:
  Enabled: false


Style/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines


Style/GuardClause:
  Enabled: false


Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses


Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented


Style/NestedParenthesizedCalls:
  Enabled: false


Style/SignalException:
  EnforcedStyle: only_fail


Style/StringLiterals:
  EnforcedStyle: single_quotes


Style/TernaryParentheses:
  Enabled: false
