#!/bin/bash -e
source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/helpers/helpers.sh"

echo_intro "SHIPPING THE CURRENT FEATURE BRANCH"

ensure_no_open_changes "You should not ship while having open files in Git."
ensure_on_feature_branch "Please checkout the feature branch to ship."

pull_main_branch
pull_feature_branch
squash_merge_feature_branch $*
push_main_branch
delete_feature_branch 'force'

echo_all_done
