#!/bin/bash
source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/helpers/helpers.sh"

function show_config {
  echo "Main branch: \"$(get_configuration "main-branch-name")\""
  echo "Non-feature branches: \"$(get_configuration "non-feature-branch-names")\""
}


if [ "$1" == "--config" ]; then
  show_config
fi

exit_with_success
