#!/bin/bash
source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/helpers/helpers.sh"


domain=$(remote_domain)
repository=$(remote_repository_name)

if [ "$domain" != github.com ] && [ "$domain" != bitbucket.org ]; then
  echo_error_header
  echo_usage "Unsupported hosting service. Repositories can only be opened from Bitbucket and GitHub"
  exit_with_error
fi

open "https://$domain/$repository"
