#!/bin/bash
source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/helpers/helpers.sh" "--bypass-automatic-configuration"

function show_config {
  show_main_branch
  show_non_feature_branches
}


function show_main_branch {
  echo "Main branch: '$main_branch_name'"
}


function show_non_feature_branches {
  echo "Non-feature branches: '$non_feature_branch_names'"
}


function add_non_feature_branch {
  local branch_name=$1

  if [ "$(is_non_feature_branch "$branch_name")" == true ]; then
    echo "'$branch_name' is already a non-feature branch"
  else
    local new_branches=$(insert_string "$non_feature_branch_names" ',' "$branch_name")
    store_configuration non-feature-branch-names "$new_branches"
    echo "Added '$branch_name' as a non-feature branch"
  fi
}


function remove_non_feature_branch {
  local branch_name=$1

  if [ "$(is_non_feature_branch "$branch_name")" == true ]; then
    local new_branches=$(remove_string "$non_feature_branch_names" ',' "$branch_name")
    store_configuration non-feature-branch-names "$new_branches"
    echo "Removed '$branch_name' from non-feature branches"
  else
    echo "Nothing to do, '$branch_name' is not a non-feature branch"
  fi
}


function show_version {
  echo "Git Town 0.4.1"
}


function show_help {
  cat "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/help.txt"
}


if [ "$1" == "--config" ]; then
  show_config
elif [ "$1" == "main-branch" ]; then
  if [ -n "$2" ]; then
    store_main_branch_name_with_confirmation_text "$2"
  else
    show_main_branch
  fi
elif [ "$1" == "non-feature-branches" ]; then
  if [ -n "$2" ]; then
    if [ -n "$3" ]; then
      if [ "$2" == "--add" ]; then
        add_non_feature_branch "$3"
      elif [ "$2" == "--remove" ]; then
        remove_non_feature_branch "$3"
      fi
    else
      echo "Missing branch name"
      echo "usage: git town non-feature-branches (--add|--remove) <branch-name>"
    fi
  else
    show_non_feature_branches
  fi
elif [ "$1" == "--version" ]; then
  show_version
elif [ -z "$1" ] || [ "$1" == "help" ]; then
  show_help
fi
