#!/bin/bash

# This file provides the "git sync" functionality.
#
# To handle errors, it defines a number of error handler methods.
# These methods are called automatically by the respective git helper methods
# when their operation fails.
#
# The error handlers create abort and continue scripts that are used when the
# user runs "git sync --abort" and "git sync --continue".


source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/helpers/helpers.sh"


abort_script_filename=`abort_script_filename_for_command sync`
continue_script_filename=`continue_script_filename_for_command sync`


# Called when pull_branch fails on the feature branch
function error_pull_feature_branch {
  create_pull_feature_branch_abort_script

  # Create the continue script
  add_to_continue_script "merge_branch $main_branch_name"
  add_to_continue_script "push_branch"
  if [ $initial_open_changes == true ]; then
    add_to_continue_script "git stash pop"
  fi

  exit_with_abort_continue_messages 'sync'
}


# Called when pull_branch fails on the main branch
function error_pull_main_branch {
  create_pull_main_branch_abort_script

  # Create the continue script
  add_to_continue_script "git checkout $initial_branch_name"
  add_to_continue_script "pull_branch"
  add_to_continue_script "merge_branch $main_branch_name"
  add_to_continue_script "push_branch"
  if [ $initial_open_changes == true ]; then
    add_to_continue_script "git stash pop"
  fi

  exit_with_abort_continue_messages 'sync'
}


# Called when merge_branch fails
function error_merge_branch {
  create_merge_main_branch_abort_script

  # Create the continue script
  add_to_continue_script "push_branch"
  if [ $initial_open_changes == true ]; then
    add_to_continue_script "git stash pop"
  fi

  exit_with_abort_continue_messages 'sync'
}


# Perform the sync operation
function perform_sync {
  stash_open_changes
  local branch_name=`get_current_branch_name`
  if [ `is_feature_branch $branch_name` == true ]; then
    sync_main_branch
    pull_branch
    merge_branch $main_branch_name
    push_branch
  else
    pull_branch 'rebase'
    push_branch
    push_tags
  fi
  restore_open_changes
}


if [ "$1" == "--abort" ]; then
  run_abort_script
elif [ "$1" == "--continue" ]; then
  ensure_no_open_changes "You must resolve the conflicts and commit your changes before continuing the git sync".
  run_continue_script
else
  perform_sync
fi

exit_with_success
