#!/bin/bash
source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/helpers/helpers.sh"


export abort_script_filename=$(abort_script_filename_for_command hack)


# Called when pull_branch fails on the main branch
function error_pull_main_branch {
  create_rebase_conflict_abort_script
  exit_with_abort_continue_messages 'hack'
}


function perform_hack {
  target_branch_name=$1

  # Exit with a help screen if parameters are missing.
  if [ -z "$target_branch_name" ]; then
    echo_usage_header
    echo_usage "git hack [feature branch name]"
    exit_with_error
  fi

  # Exit if the branch with that name already exists.
  if [ "$(has_branch "$target_branch_name")" == true ]; then
    echo_error_header
    echo_error "A branch named '$target_branch_name' already exists"
    exit_with_error
  fi

  stash_open_changes
  sync_main_branch
  create_and_checkout_feature_branch "$target_branch_name"
  restore_open_changes
}


if [ "$1" == "--abort" ]; then
  run_abort_script
else
  perform_hack "$*"
fi

exit_with_success
