#!/bin/bash -e
source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/helpers/helpers.sh"

echo_intro "UPDATING THE CURRENT GIT BRANCH"
stash_open_changes

if [ "$current_branch_name" = "$main_branch_name" ]; then
  update_main_branch
else
  update_main_branch
  update_feature_branch
fi

restore_open_changes
echo_all_done
