#!/bin/bash
source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/helpers/helpers.sh"

branch_name=`get_current_branch_name`

ensure_on_feature_branch "You can only kill feature branches."


if [ $initial_open_changes = true ]; then
  git add -A
  git commit -m 'temp'
fi

checkout_main_branch
delete_branch $branch_name force

exit_with_success
