#!/bin/bash
source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/helpers/helpers.sh"

stash_open_changes
sync_main_branch

for remote_branch_name in `git branch -r --merged $main_branch_name | grep -v HEAD | tr -d ' ' | sed 's/origin\///g'`
do
  if [ `is_feature_branch $remote_branch_name` == true ]; then
    delete_remote_branch $remote_branch_name
  fi
done

for local_branch_name in `git branch --merged $main_branch_name | tr -d ' ' | sed 's/\*//g'`
do
  if [ `is_feature_branch $local_branch_name` == true ]; then
    if [ `get_current_branch_name` == $local_branch_name ]; then
      checkout_main_branch
    fi
    delete_local_branch $local_branch_name
  fi
done

restore_open_changes
