#!/bin/bash
source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/helpers/helpers.sh"

function should_delete_branch {
  local branch_name=$1

  if [ "$(is_feature_branch "$branch_name")" = true ]; then
    if [ "$initial_branch_name" = "$branch_name" -a "$initial_open_changes" = true ]; then
      echo false
    else
      echo true
    fi
  else
    echo false
  fi
}


fetch_repo
if [ "$initial_branch_name" != "$main_branch_name" ]; then
  stash_open_changes
  checkout_main_branch
fi

for local_branch_name in $(local_merged_branches); do
  if [ "$(should_delete_branch "$local_branch_name")" = true ]; then
    delete_branch "$local_branch_name"
  fi
done

for remote_branch_name in $(remote_merged_branches); do
  if [ "$(should_delete_branch "$remote_branch_name")" = true ]; then
    delete_remote_branch "$remote_branch_name"
  fi
done

if [ "$(has_branch "$initial_branch_name")" = true ]; then
  checkout_branch "$initial_branch_name"
fi

if [ "$initial_branch_name" != "$main_branch_name" ]; then
  restore_open_changes
fi

exit_with_success
