#!/bin/bash
source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/helpers/helpers.sh"

stash_open_changes
checkout_main_branch
sync_non_feature_branch

for local_branch_name in $(local_branches); do
  if [ "$(is_feature_branch "$local_branch_name")" == true ]; then
    checkout_branch "$local_branch_name"
    pull_branch
    merge_branch "$main_branch_name"
    push_branch
  fi
done

checkout_branch "$initial_branch_name"
restore_open_changes
exit_with_success
