#!/bin/bash
source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/helpers/helpers.sh"


# Called when rebase_branch fails
function error_rebase_branch {
  create_rebase_conflict_abort_script
  exit_with_script_messages
}


# Outputs error and exits
function error_with_upstream_required {
  echo_error_header
  echo_error "Please add a remote 'upstream'"
  exit_with_error
}


# Sync the current branch with the upstream repository
function sync_fork {
  if [ "$(git remote -v | grep -c 'upstream')" == 0 ]; then
    error_with_upstream_required
  fi

  local branch_name=$(get_current_branch_name)
  stash_open_changes_if_needed
  checkout_main_branch
  fetch_upstream
  rebase_branch "upstream/$main_branch_name"
  push_branch
  checkout_branch "$branch_name"
  restore_open_changes_if_needed
}


if [ "$1" == "--abort" ]; then
  run_abort_script
else
  sync_fork
fi

exit_with_success
