Feature: display all executed Git commands

  Background:
    Given a Git repo with origin
    And the branches
      | NAME    | TYPE    | PARENT | LOCATIONS     |
      | current | feature | main   | local, origin |
      | other   | feature | main   | local, origin |
    And the commits
      | BRANCH  | LOCATION      | MESSAGE        |
      | current | local, origin | current commit |
      | other   | local, origin | other commit   |
    And the current branch is "current"
    And the current branch is "current" and the previous branch is "other"
    When I run "git-town delete --verbose"

  Scenario: result
    Then Git Town runs the commands
      | BRANCH  | TYPE     | COMMAND                                                                                                                                                                                                                                                                                                                                          |
      |         | backend  | git version                                                                                                                                                                                                                                                                                                                                      |
      |         | backend  | git rev-parse --show-toplevel                                                                                                                                                                                                                                                                                                                    |
      |         | backend  | git config -lz --global                                                                                                                                                                                                                                                                                                                          |
      |         | backend  | git config -lz --local                                                                                                                                                                                                                                                                                                                           |
      |         | backend  | git config -lz                                                                                                                                                                                                                                                                                                                                   |
      |         | backend  | git status -z --ignore-submodules                                                                                                                                                                                                                                                                                                                |
      |         | backend  | git rev-parse --verify -q MERGE_HEAD                                                                                                                                                                                                                                                                                                             |
      |         | backend  | git rev-parse --absolute-git-dir                                                                                                                                                                                                                                                                                                                 |
      |         | backend  | git remote get-url origin                                                                                                                                                                                                                                                                                                                        |
      |         | backend  | git remote                                                                                                                                                                                                                                                                                                                                       |
      |         | backend  | git branch --show-current                                                                                                                                                                                                                                                                                                                        |
      | current | frontend | git fetch --prune --tags                                                                                                                                                                                                                                                                                                                         |
      |         | backend  | git stash list                                                                                                                                                                                                                                                                                                                                   |
      |         | backend  | git for-each-ref --format=refname:%(refname)%00branchname:%(refname:lstrip=2)%00sha:%(objectname)%00head:%(if)%(HEAD)%(then)Y%(else)N%(end)%00worktreepath:%(worktreepath)%00symref:%(if)%(symref)%(then)Y%(else)N%(end)%00upstream:%(upstream:lstrip=2)%00track:%(upstream:track,nobracket) --sort=refname refs/heads/ refs/remotes/ |
      |         | backend  | git rev-parse --verify --abbrev-ref @{-1}                                                                                                                                                                                                                                                                                                        |
      |         | frontend | git push origin :current                                                                                                                                                                                                                                                                                                                         |
      |         | frontend | git checkout other                                                                                                                                                                                                                                                                                                                               |
      | other   | frontend | git branch -D current                                                                                                                                                                                                                                                                                                                            |
      |         | backend  | git config --unset git-town-branch.current.parent                                                                                                                                                                                                                                                                                                |
      |         | backend  | git config --unset git-town-branch.current.branchtype                                                                                                                                                                                                                                                                                            |
      |         | backend  | git rev-parse --verify -q refs/heads/current                                                                                                                                                                                                                                                                                                     |
      |         | backend  | git for-each-ref --format=refname:%(refname)%00branchname:%(refname:lstrip=2)%00sha:%(objectname)%00head:%(if)%(HEAD)%(then)Y%(else)N%(end)%00worktreepath:%(worktreepath)%00symref:%(if)%(symref)%(then)Y%(else)N%(end)%00upstream:%(upstream:lstrip=2)%00track:%(upstream:track,nobracket) --sort=refname refs/heads/ refs/remotes/ |
      |         | backend  | git config -lz --global                                                                                                                                                                                                                                                                                                                          |
      |         | backend  | git config -lz --local                                                                                                                                                                                                                                                                                                                           |
      |         | backend  | git stash list                                                                                                                                                                                                                                                                                                                                   |
    And Git Town prints:
      """
      Ran 25 shell commands.
      """
