package proposallineage2

import (
	"strings"

	"github.com/git-town/git-town/v22/internal/git/gitdomain"
)

func Render(tree TreeNodeWithProposal, currentBranch gitdomain.LocalBranchName) string {
	var builder strings.Builder
	builder.WriteString("\n-------------------------\n")
	foundCurrent := false
	renderNode(&builder, tree, currentBranch, 0, &foundCurrent)
	builder.WriteString("\n<sup>[Stack](https://www.git-town.com/how-to/github-actions-breadcrumb.html) generated by [Git Town](https://github.com/git-town/git-town)</sup>\n")
	return builder.String()
}

func renderNode(builder *strings.Builder, node TreeNodeWithProposal, currentBranch gitdomain.LocalBranchName, depth int, foundCurrent *bool) {
	builder.WriteString(strings.Repeat(" ", depth*2))
	builder.WriteString("- ")
	if proposal, hasProposal := node.Proposal.Get(); hasProposal {
		builder.WriteString(proposal.Data.Data().URL)
	} else {
		builder.WriteString(node.Branch.String())
	}
	isCurrentBranch := node.Branch == currentBranch && !*foundCurrent
	if isCurrentBranch {
		builder.WriteString(" :point_left:")
		*foundCurrent = true
	}
	builder.WriteString("\n")
	// Determine if we should render children
	if *foundCurrent {
		// After finding current, only render children with proposals
		if isCurrentBranch {
			for _, child := range node.Children {
				if _, hasProposal := child.Proposal.Get(); hasProposal {
					renderNode(builder, child, currentBranch, depth+1, foundCurrent)
				}
			}
		}
		// Don't render anything else after finding current
	} else {
		// Before finding current, render all children
		for _, child := range node.Children {
			renderNode(builder, child, currentBranch, depth+1, foundCurrent)
		}
	}
}
