package proposallineage2_test

import (
	"testing"

	"github.com/git-town/git-town/v22/internal/forge/forgedomain"
	"github.com/git-town/git-town/v22/internal/proposallineage2"
	. "github.com/git-town/git-town/v22/pkg/prelude"
	"github.com/shoenig/test/must"
)

func TestRender(t *testing.T) {
	t.Parallel()
	t.Run("all branches have proposals", func(t *testing.T) {
		tree := proposallineage2.TreeNodeWithProposal{
			Branch: "main",
			Children: []proposallineage2.TreeNodeWithProposal{
				{
					Branch: "feature-1",
					Children: []proposallineage2.TreeNodeWithProposal{
						{
							Branch:   "feature-1",
							Children: []proposallineage2.TreeNodeWithProposal{},
							Proposal: Some(forgedomain.Proposal{
								Data: forgedomain.ProposalData{
									URL: "https://www.github.com/git-town/pull/2",
								},
							}),
						},
					},
					Proposal: Some(forgedomain.Proposal{
						Data: forgedomain.ProposalData{
							URL: "https://www.github.com/git-town/pull/1",
						},
					}),
				},
			},
			Proposal: None[forgedomain.Proposal](),
		}
		want := `

-------------------------
 - main
   - https://www.github.com/git-town/pull/1 :point_left:
     - https://www.github.com/git-town/pull/2

<sup>[Stack](https://www.git-town.com/how-to/github-actions-breadcrumb.html) generated by [Git Town](https://github.com/git-town/git-town)</sup>
`[1:]
		have := proposallineage2.Render(tree, "feature-1")
		must.Eq(t, want, have)
	})

	t.Run("no proposals", func(t *testing.T) {
		tree := proposallineage2.TreeNodeWithProposal{
			Branch: "main",
			Children: []proposallineage2.TreeNodeWithProposal{
				{
					Branch: "feature-1",
					Children: []proposallineage2.TreeNodeWithProposal{
						{
							Branch: "feature-2",
							Children: []proposallineage2.TreeNodeWithProposal{
								{
									Branch:   "feature-3",
									Children: []proposallineage2.TreeNodeWithProposal{},
									Proposal: None[forgedomain.Proposal](),
								},
							},
							Proposal: None[forgedomain.Proposal](),
						},
					},
					Proposal: None[forgedomain.Proposal](),
				},
			},
			Proposal: None[forgedomain.Proposal](),
		}
		want := `

-------------------------
 - main
   - feature-1
		 - feature-2 :point_left:

<sup>[Stack](https://www.git-town.com/how-to/github-actions-breadcrumb.html) generated by [Git Town](https://github.com/git-town/git-town)</sup>
`[1:]
		have := proposallineage2.Render(tree, "feature-2")
		must.Eq(t, want, have)
	})
}
