package forgedomain_test

import (
	"fmt"
	"testing"

	"github.com/shoenig/test/must"

	"github.com/git-town/git-town/v21/internal/config/configdomain"
	"github.com/git-town/git-town/v21/internal/forge/forgedomain"
	"github.com/git-town/git-town/v21/internal/git/gitdomain"
	"github.com/git-town/git-town/v21/internal/subshell/subshelldomain"
	. "github.com/git-town/git-town/v21/pkg/prelude"
)

type mockConnectorProposalStackLineageBuilder struct{}

func (self *mockConnectorProposalStackLineageBuilder) CreateProposal(_ forgedomain.CreateProposalArgs) error {
	return nil
}

func (self *mockConnectorProposalStackLineageBuilder) DefaultProposalMessage(_ forgedomain.ProposalData) string {
	return "mock"
}

func (self *mockConnectorProposalStackLineageBuilder) FindProposalFn() Option[func(branch, target gitdomain.LocalBranchName) (Option[forgedomain.Proposal], error)] {
	return Some(func(branch, target gitdomain.LocalBranchName) (Option[forgedomain.Proposal], error) {
		var prNumber int
		for _, char := range branch {
			prNumber += int(char)
		}
		return Some(forgedomain.Proposal{
			Data: forgedomain.ProposalData{
				Body:         None[string](),
				MergeWithAPI: false,
				Number:       1,
				Source:       branch,
				Target:       target,
				Title:        "Test Mocker",
				URL:          fmt.Sprintf("https://www.github.com/git-town/pull/%d", prNumber),
			},
			ForgeType: forgedomain.ForgeTypeCodeberg,
		}), nil
	})
}

func (self *mockConnectorProposalStackLineageBuilder) OpenRepository(_ subshelldomain.Runner) error {
	return nil
}

func (self *mockConnectorProposalStackLineageBuilder) SearchProposalFn() Option[func(_ gitdomain.LocalBranchName) (Option[forgedomain.Proposal], error)] {
	return None[func(_ gitdomain.LocalBranchName) (Option[forgedomain.Proposal], error)]()
}

func (self *mockConnectorProposalStackLineageBuilder) SquashMergeProposalFn() Option[func(_ int, _ gitdomain.CommitMessage) error] {
	return None[func(_ int, _ gitdomain.CommitMessage) error]()
}

func (self *mockConnectorProposalStackLineageBuilder) UpdateProposalBodyFn() Option[func(_ forgedomain.ProposalInterface, _ string) error] {
	return None[func(_ forgedomain.ProposalInterface, _ string) error]()
}

func (self *mockConnectorProposalStackLineageBuilder) UpdateProposalSourceFn() Option[func(_ forgedomain.ProposalInterface, _ gitdomain.LocalBranchName) error] {
	return None[func(_ forgedomain.ProposalInterface, _ gitdomain.LocalBranchName) error]()
}

func (self *mockConnectorProposalStackLineageBuilder) UpdateProposalTargetFn() Option[func(_ forgedomain.ProposalInterface, _ gitdomain.LocalBranchName) error] {
	return None[func(_ forgedomain.ProposalInterface, _ gitdomain.LocalBranchName) error]()
}

func (self *mockConnectorProposalStackLineageBuilder) VerifyConnection() forgedomain.VerifyConnectionResult {
	return forgedomain.VerifyConnectionResult{
		AuthenticatedUser:   None[string](),
		AuthenticationError: nil,
		AuthorizationError:  nil,
	}
}

func TestProposalStackLineageBuilder_CheckLineageAndProposals(t *testing.T) {
	t.Parallel()
	// arrange
	mainBranch := gitdomain.NewLocalBranchName("main")
	featureBranchA := gitdomain.NewLocalBranchName("a")
	featureBranchB := gitdomain.NewLocalBranchName("b")
	lineage := configdomain.NewLineageWith(configdomain.LineageData{
		featureBranchA: mainBranch,
		featureBranchB: featureBranchA,
	})
	var connector forgedomain.Connector = &mockConnectorProposalStackLineageBuilder{}
	args := configdomain.ProposalStackLineageArgs{
		Connector:                connector,
		CurrentBranch:            featureBranchA,
		Lineage:                  lineage,
		MainAndPerennialBranches: gitdomain.NewLocalBranchNames(mainBranch.String()),
	}
	want := `

-------------------------
 - main
   - https://www.github.com/git-town/pull/97 :point_left:
     - https://www.github.com/git-town/pull/98

Stack generated by [Git-Town](https://github.com/git-town/git-town)
`[1:]

	// act
	have := configdomain.NewProposalStackLineageBuilder(args)

	// assert
	builder, hasBuilder := have.Get()
	must.True(t, hasBuilder)
	must.True(t, builder.GetProposal(mainBranch).IsNone())
	must.True(t, builder.GetProposal(featureBranchB).IsSome())
	must.True(t, builder.GetProposal(featureBranchA).IsSome())

	actual := builder.Build(args)
	must.EqOp(t, want, actual)
}

func TestProposalStackLineageBuilder_CurrentBranchHasMultipleDirectDescendants(t *testing.T) {
	t.Parallel()
	// arrange
	/*
				git-town branch:
					main
							a
									b
											c
									d
							e
									f
		There is a stack: main -> a -> [b -> c, d]
		There is a separate stack: main -> e -> f
	*/
	mainBranch := gitdomain.NewLocalBranchName("main")
	featureBranchA := gitdomain.NewLocalBranchName("a")
	featureBranchB := gitdomain.NewLocalBranchName("b")
	featureBranchC := gitdomain.NewLocalBranchName("c")
	featureBranchD := gitdomain.NewLocalBranchName("d")
	featureBranchE := gitdomain.NewLocalBranchName("e")
	featureBranchF := gitdomain.NewLocalBranchName("f")
	lineage := configdomain.NewLineageWith(configdomain.LineageData{
		// first stack
		featureBranchA: mainBranch,
		featureBranchB: featureBranchA,
		featureBranchC: featureBranchB,
		featureBranchD: featureBranchA,
		// second stack
		featureBranchE: mainBranch,
		featureBranchF: featureBranchE,
	})

	t.Run("Stack Proposal For Branch A", func(t *testing.T) {
		t.Parallel()
		var connector forgedomain.Connector = &mockConnectorProposalStackLineageBuilder{}
		args := configdomain.ProposalStackLineageArgs{
			Connector:                connector,
			CurrentBranch:            featureBranchA,
			Lineage:                  lineage,
			MainAndPerennialBranches: gitdomain.NewLocalBranchNames(mainBranch.String()),
		}
		want := `
-------------------------
 - main
   - https://www.github.com/git-town/pull/97 :point_left:
     - https://www.github.com/git-town/pull/98
       - https://www.github.com/git-town/pull/99
     - https://www.github.com/git-town/pull/100

Stack generated by [Git-Town](https://github.com/git-town/git-town)
`
		have := configdomain.NewProposalStackLineageBuilder(args)
		builder, hasBuilder := have.Get()
		must.True(t, hasBuilder)
		// actual
		actual := builder.Build(args)
		// assert
		must.EqOp(t, want, actual)
	})

	t.Run("Stack Proposal For Branch B", func(t *testing.T) {
		t.Parallel()
		var connector forgedomain.Connector = &mockConnectorProposalStackLineageBuilder{}
		args := configdomain.ProposalStackLineageArgs{
			Connector:                connector,
			CurrentBranch:            featureBranchB,
			Lineage:                  lineage,
			MainAndPerennialBranches: gitdomain.NewLocalBranchNames(mainBranch.String()),
		}
		want := `
-------------------------
 - main
   - https://www.github.com/git-town/pull/97
     - https://www.github.com/git-town/pull/98 :point_left:
       - https://www.github.com/git-town/pull/99
     - https://www.github.com/git-town/pull/100

Stack generated by [Git-Town](https://github.com/git-town/git-town)
`
		have := configdomain.NewProposalStackLineageBuilder(args)
		builder, hasBuilder := have.Get()
		must.True(t, hasBuilder)
		// actual
		actual := builder.Build(args)
		// assert
		must.EqOp(t, want, actual)
	})

	t.Run("Stack Proposal For Branch C", func(t *testing.T) {
		t.Parallel()
		var connector forgedomain.Connector = &mockConnectorProposalStackLineageBuilder{}
		args := configdomain.ProposalStackLineageArgs{
			Connector:                connector,
			CurrentBranch:            featureBranchC,
			Lineage:                  lineage,
			MainAndPerennialBranches: gitdomain.NewLocalBranchNames(mainBranch.String()),
		}
		want := `
-------------------------
 - main
   - https://www.github.com/git-town/pull/97
     - https://www.github.com/git-town/pull/98
       - https://www.github.com/git-town/pull/99 :point_left:
     - https://www.github.com/git-town/pull/100

Stack generated by [Git-Town](https://github.com/git-town/git-town)
`
		have := configdomain.NewProposalStackLineageBuilder(args)
		builder, hasBuilder := have.Get()
		must.True(t, hasBuilder)
		// actual
		actual := builder.Build(args)
		// assert
		must.EqOp(t, want, actual)
	})

	t.Run("Stack Proposal For Branch D", func(t *testing.T) {
		t.Parallel()
		var connector forgedomain.Connector = &mockConnectorProposalStackLineageBuilder{}
		args := configdomain.ProposalStackLineageArgs{
			Connector:                connector,
			CurrentBranch:            featureBranchD,
			Lineage:                  lineage,
			MainAndPerennialBranches: gitdomain.NewLocalBranchNames(mainBranch.String()),
		}
		want := `
-------------------------
 - main
   - https://www.github.com/git-town/pull/97
     - https://www.github.com/git-town/pull/100 :point_left:
     - https://www.github.com/git-town/pull/98
       - https://www.github.com/git-town/pull/99

Stack generated by [Git-Town](https://github.com/git-town/git-town)
`
		have := configdomain.NewProposalStackLineageBuilder(args)
		builder, hasBuilder := have.Get()
		must.True(t, hasBuilder)
		// actual
		actual := builder.Build(args)
		// assert
		must.EqOp(t, want, actual)
	})

	t.Run("Stack Proposal For Branch E", func(t *testing.T) {
		t.Parallel()
		var connector forgedomain.Connector = &mockConnectorProposalStackLineageBuilder{}
		args := configdomain.ProposalStackLineageArgs{
			Connector:                connector,
			CurrentBranch:            featureBranchE,
			Lineage:                  lineage,
			MainAndPerennialBranches: gitdomain.NewLocalBranchNames(mainBranch.String()),
		}
		want := `
-------------------------
 - main
   - https://www.github.com/git-town/pull/101 :point_left:
     - https://www.github.com/git-town/pull/102

Stack generated by [Git-Town](https://github.com/git-town/git-town)
`
		have := configdomain.NewProposalStackLineageBuilder(args)
		builder, hasBuilder := have.Get()
		must.True(t, hasBuilder)
		// actual
		actual := builder.Build(args)
		// assert
		must.EqOp(t, want, actual)
	})

	t.Run("Stack Proposal For Branch F", func(t *testing.T) {
		t.Parallel()
		var connector forgedomain.Connector = &mockConnectorProposalStackLineageBuilder{}
		args := configdomain.ProposalStackLineageArgs{
			Connector:                connector,
			CurrentBranch:            featureBranchF,
			Lineage:                  lineage,
			MainAndPerennialBranches: gitdomain.NewLocalBranchNames(mainBranch.String()),
		}
		want := `
-------------------------
 - main
   - https://www.github.com/git-town/pull/101
     - https://www.github.com/git-town/pull/102 :point_left:

Stack generated by [Git-Town](https://github.com/git-town/git-town)
`
		have := configdomain.NewProposalStackLineageBuilder(args)
		builder, hasBuilder := have.Get()
		must.True(t, hasBuilder)
		// actual
		actual := builder.Build(args)
		// assert
		must.EqOp(t, want, actual)
	})
}

func TestProposalStackLineageBuilder_NoLineage(t *testing.T) {
	t.Parallel()
	// arrange
	lineage := configdomain.NewLineageWith(configdomain.LineageData{})
	var connector forgedomain.Connector = &mockConnectorProposalStackLineageBuilder{}
	args := configdomain.ProposalStackLineageArgs{
		Connector:                connector,
		CurrentBranch:            gitdomain.NewLocalBranchName("main"),
		Lineage:                  lineage,
		MainAndPerennialBranches: lineage.Roots(),
	}
	expected := None[configdomain.ProposalStackLineageBuilder]()

	// act
	actual := configdomain.NewProposalStackLineageBuilder(args)

	// assert
	must.EqOp(t, expected, actual)
}

func TestProposalStackLineageBuilder_NoLineageForMainAndPerennialBranches(t *testing.T) {
	t.Parallel()
	// arrange
	mainBranch := gitdomain.NewLocalBranchName("main")
	featureBranchA := gitdomain.NewLocalBranchName("a")
	lineage := configdomain.NewLineageWith(configdomain.LineageData{
		featureBranchA: mainBranch,
	})
	var connector forgedomain.Connector = &mockConnectorProposalStackLineageBuilder{}
	args := configdomain.ProposalStackLineageArgs{
		Connector:                connector,
		CurrentBranch:            mainBranch,
		Lineage:                  lineage,
		MainAndPerennialBranches: lineage.Roots(),
	}
	expected := None[configdomain.ProposalStackLineageBuilder]()

	// act
	actual := configdomain.NewProposalStackLineageBuilder(args)

	// assert
	must.EqOp(t, expected, actual)
}
