name: Bug Report
description: Report a bug
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to report this bug!
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Please provide detailed steps to reproduce the problem
    validations:
      required: true
  - type: textarea
    attributes:
      label: Command output
      description: Output of the failing Git Town command with the `--verbose` option enabled
      render: shell
  - type: textarea
    attributes:
      label: Additional info
      description: Additional observations, comments, or suggestions you want to share
