name: Bug Report
description: Report a bug
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to report this bug!
  - type: textarea
    attributes:
      label: Steps to reproduce
      description:
        Please provide detailed steps to reproduce the problem.
        If a textual description isn't enough, please consider creating a shell script that reproduces the issue.
        You can use [this template](https://github.com/git-town/git-town/blob/main/docs/repro.sh) to create one quickly.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Command output
      description: Output of the failing Git Town command with the `--verbose` option enabled
      render: shell
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      description: Additional observations, suggestions, or comments you want to share
