name: Other
description: Any other feedback
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to provide feedback!
  - type: textarea
    attributes:
      label: Text
      description: Your message to us
    validations:
      required: true
