Feature: delete the current feature branch from a stack and update proposals

  Background:
    Given a Git repo with origin
    And the origin is "git@github.com:git-town/git-town.git"
    And the branches
      | NAME  | TYPE    | PARENT | LOCATIONS     |
      | alpha | feature | main   | local, origin |
      | beta  | feature | alpha  | local, origin |
    And the proposals
      | ID | SOURCE BRANCH | TARGET BRANCH | BODY       | URL                      |
      |  1 | alpha         | main          | alpha body | https://example.com/pr/1 |
      |  2 | beta          | alpha         | beta body  | https://example.com/pr/2 |
    And Git setting "git-town.proposals-show-lineage" is "cli"
    And the current branch is "alpha"
    When I run "git-town delete"

  Scenario: result
    Then Git Town runs the commands
      | BRANCH | COMMAND                                                                    |
      | alpha  | git fetch --prune --tags                                                   |
      |        | Finding proposal from beta into alpha ... #2 (Proposal from beta to alpha) |
      |        | Updating target branch of proposal #2 to main ... ok                       |
      |        | git push origin :alpha                                                     |
      |        | git checkout beta                                                          |
      | beta   | git branch -D alpha                                                        |
      |        | Finding proposals for alpha ... main                                       |
      |        | Update body for #1 ... ok                                                  |
      |        | Finding proposals for beta ... main                                        |
      |        | Finding proposal from beta into main ... #2 (Proposal from beta to alpha)  |
      |        | Update body for #2 ... ok                                                  |
    And this lineage exists now
      """
      main
        beta
      """
    And the branches are now
      | REPOSITORY    | BRANCHES   |
      | local, origin | main, beta |
    And no uncommitted files exist now
    And the proposals are now
      | ID | SOURCE BRANCH | TARGET BRANCH | BODY                                                                                                                                                                                                                                                                                                        |
      |  1 | alpha         | main          | alpha body\n\n<!-- branch-stack-start -->\n\n-------------------------\n- alpha :point_left:\n\n<sup>[Stack](https://www.git-town.com/how-to/github-actions-breadcrumb.html) generated by [Git Town](https://github.com/git-town/git-town)</sup>\n\n<!-- branch-stack-end -->\n                             |
      |  2 | beta          | main          | beta body\n\n<!-- branch-stack-start -->\n\n-------------------------\n- main\n  - https://example.com/pr/2 :point_left:\n\n<sup>[Stack](https://www.git-town.com/how-to/github-actions-breadcrumb.html) generated by [Git Town](https://github.com/git-town/git-town)</sup>\n\n<!-- branch-stack-end -->\n |

  Scenario: undo
    When I run "git-town undo"
    Then Git Town runs the commands
      | BRANCH | COMMAND                                               |
      | beta   | git branch alpha {{ sha 'initial commit' }}           |
      |        | git push -u origin alpha                              |
      |        | Updating target branch of proposal #2 to alpha ... ok |
      |        | git checkout alpha                                    |
    And the initial branches and lineage exist now
    And the initial commits exist now
    And the proposals are now
      | ID | SOURCE BRANCH | TARGET BRANCH | BODY                                                                                                                                                                                                                                                                                                        |
      |  1 | alpha         | main          | alpha body\n\n<!-- branch-stack-start -->\n\n-------------------------\n- alpha :point_left:\n\n<sup>[Stack](https://www.git-town.com/how-to/github-actions-breadcrumb.html) generated by [Git Town](https://github.com/git-town/git-town)</sup>\n\n<!-- branch-stack-end -->\n                             |
      |  2 | beta          | alpha         | beta body\n\n<!-- branch-stack-start -->\n\n-------------------------\n- main\n  - https://example.com/pr/2 :point_left:\n\n<sup>[Stack](https://www.git-town.com/how-to/github-actions-breadcrumb.html) generated by [Git Town](https://github.com/git-town/git-town)</sup>\n\n<!-- branch-stack-end -->\n |
