Feature: delete the current feature branch from a stack and update proposals

  Background:
    Given a Git repo with origin
    And the origin is "git@github.com:git-town/git-town.git"
    And the branches
      | NAME  | TYPE    | PARENT | LOCATIONS     |
      | alpha | feature | main   | local, origin |
      | beta  | feature | alpha  | local, origin |
      | gamma | feature | beta   | local, origin |
      | delta | feature | gamma  | local, origin |
    And the proposals
      | ID | SOURCE BRANCH | TARGET BRANCH | BODY       | URL                      |
      |  1 | alpha         | main          | alpha body | https://example.com/pr/1 |
      |  2 | beta          | alpha         | beta body  | https://example.com/pr/2 |
      |  3 | gamma         | beta          | gamma body | https://example.com/pr/3 |
      |  4 | delta         | gamma         | delta body | https://example.com/pr/4 |
    And Git setting "git-town.proposals-show-lineage" is "cli"
    And the current branch is "beta"
    When I run "git-town delete"

  Scenario: result
    Then Git Town runs the commands
      | BRANCH | COMMAND                                                                      |
      | beta   | git fetch --prune --tags                                                     |
      |        | Finding proposal from gamma into beta ... #3 (Proposal from gamma to beta)   |
      |        | Updating target branch of proposal #3 to alpha ... ok                        |
      |        | git push origin :beta                                                        |
      |        | git checkout delta                                                           |
      | delta  | git branch -D beta                                                           |
      |        | Finding proposals for alpha ... main                                         |
      |        | Finding proposal from alpha into main ... #1 (Proposal from alpha to main)   |
      |        | Finding proposal from gamma into alpha ... #3 (Proposal from gamma to beta)  |
      |        | Finding proposal from delta into gamma ... #4 (Proposal from delta to gamma) |
      |        | Update body for #1 ... ok                                                    |
      |        | Finding proposals for beta ... alpha                                         |
      |        | Update body for #2 ... ok                                                    |
      |        | Finding proposals for delta ... gamma                                        |
      |        | Finding proposal from alpha into main ... #1 (Proposal from alpha to main)   |
      |        | Update body for #4 ... ok                                                    |
      |        | Finding proposals for gamma ... alpha                                        |
      |        | Finding proposal from delta into gamma ... #4 (Proposal from delta to gamma) |
      |        | Update body for #3 ... ok                                                    |
    And this lineage exists now
      """
      main
        alpha
          gamma
            delta
      """
    And the branches are now
      | REPOSITORY    | BRANCHES                  |
      | local, origin | main, alpha, delta, gamma |
    And no uncommitted files exist now
    And the proposals are now
      | ID | SOURCE BRANCH | TARGET BRANCH | BODY                                                                                                                                                                                                                                                                                                                                                                           |
      |  1 | alpha         | main          | alpha body\n\n<!-- branch-stack-start -->\n\n-------------------------\n- main\n  - https://example.com/pr/1 :point_left:\n    - https://example.com/pr/3\n      - https://example.com/pr/4\n\n<sup>[Stack](https://www.git-town.com/how-to/github-actions-breadcrumb.html) generated by [Git Town](https://github.com/git-town/git-town)</sup>\n\n<!-- branch-stack-end -->\n |
      |  2 | beta          | alpha         | beta body\n\n<!-- branch-stack-start -->\n\n-------------------------\n- beta :point_left:\n\n<sup>[Stack](https://www.git-town.com/how-to/github-actions-breadcrumb.html) generated by [Git Town](https://github.com/git-town/git-town)</sup>\n\n<!-- branch-stack-end -->\n                                                                                                  |
      |  3 | gamma         | alpha         | gamma body\n\n<!-- branch-stack-start -->\n\n-------------------------\n- main\n  - https://example.com/pr/1\n    - https://example.com/pr/3 :point_left:\n      - https://example.com/pr/4\n\n<sup>[Stack](https://www.git-town.com/how-to/github-actions-breadcrumb.html) generated by [Git Town](https://github.com/git-town/git-town)</sup>\n\n<!-- branch-stack-end -->\n |
      |  4 | delta         | gamma         | delta body\n\n<!-- branch-stack-start -->\n\n-------------------------\n- main\n  - https://example.com/pr/1\n    - https://example.com/pr/3\n      - https://example.com/pr/4 :point_left:\n\n<sup>[Stack](https://www.git-town.com/how-to/github-actions-breadcrumb.html) generated by [Git Town](https://github.com/git-town/git-town)</sup>\n\n<!-- branch-stack-end -->\n |

  Scenario: undo
    When I run "git-town undo"
    Then Git Town runs the commands
      | BRANCH | COMMAND                                              |
      | delta  | git branch beta {{ sha 'initial commit' }}           |
      |        | git push -u origin beta                              |
      |        | Updating target branch of proposal #3 to beta ... ok |
      |        | git checkout beta                                    |
    And the initial branches and lineage exist now
    And the initial commits exist now
    And the proposals are now
      | ID | SOURCE BRANCH | TARGET BRANCH | BODY                                                                                                                                                                                                                                                                                                                                                                           |
      |  1 | alpha         | main          | alpha body\n\n<!-- branch-stack-start -->\n\n-------------------------\n- main\n  - https://example.com/pr/1 :point_left:\n    - https://example.com/pr/3\n      - https://example.com/pr/4\n\n<sup>[Stack](https://www.git-town.com/how-to/github-actions-breadcrumb.html) generated by [Git Town](https://github.com/git-town/git-town)</sup>\n\n<!-- branch-stack-end -->\n |
      |  2 | beta          | alpha         | beta body\n\n<!-- branch-stack-start -->\n\n-------------------------\n- beta :point_left:\n\n<sup>[Stack](https://www.git-town.com/how-to/github-actions-breadcrumb.html) generated by [Git Town](https://github.com/git-town/git-town)</sup>\n\n<!-- branch-stack-end -->\n                                                                                                  |
      |  3 | gamma         | beta          | gamma body\n\n<!-- branch-stack-start -->\n\n-------------------------\n- main\n  - https://example.com/pr/1\n    - https://example.com/pr/3 :point_left:\n      - https://example.com/pr/4\n\n<sup>[Stack](https://www.git-town.com/how-to/github-actions-breadcrumb.html) generated by [Git Town](https://github.com/git-town/git-town)</sup>\n\n<!-- branch-stack-end -->\n |
      |  4 | delta         | gamma         | delta body\n\n<!-- branch-stack-start -->\n\n-------------------------\n- main\n  - https://example.com/pr/1\n    - https://example.com/pr/3\n      - https://example.com/pr/4 :point_left:\n\n<sup>[Stack](https://www.git-town.com/how-to/github-actions-breadcrumb.html) generated by [Git Town](https://github.com/git-town/git-town)</sup>\n\n<!-- branch-stack-end -->\n |
