Feature: sync stacked changes without updating proposals of observed branches

  Background:
    Given a Git repo with origin
    And the origin is "git@github.com:git-town/git-town.git"
    And the branches
      | NAME     | TYPE     | PARENT   | LOCATIONS     |
      | observed | observed | main     | local, origin |
      | child    | feature  | observed | local, origin |
    And the commits
      | BRANCH   | LOCATION      | MESSAGE         |
      | observed | local, origin | observed commit |
      | child    | local, origin | child commit    |
    And the proposals
      | ID | SOURCE BRANCH | TARGET BRANCH | TITLE             | BODY          | URL                      |
      | 1  | observed      | main          | observed proposal | observed body | https://example.com/pr/1 |
      | 2  | child         | observed      | child proposal    | child body    | https://example.com/pr/2 |
    And Git setting "git-town.proposal-breadcrumb" is "stacks"
    And Git setting "git-town.sync-feature-strategy" is "rebase"
    And the current branch is "child"
    When I run "git-town sync --stack"

  Scenario: result
    Then Git Town runs the commands
      | BRANCH | COMMAND                                                                                  |
      | child  | git fetch --prune --tags                                                                 |
      |        | git -c rebase.updateRefs=false rebase --onto observed {{ sha-initial 'initial commit' }} |
      |        | git push --force-with-lease --force-if-includes                                          |
      |        | Finding all proposals for child ... observed                                              |
      |        | Finding proposal from observed into main ... #1 (observed proposal)                       |
      |        | Finding proposal from child into observed ... #2 (child proposal)                         |
      |        | Update body for #2 ... ok                                                                |
    And the proposals are now
      """
      url: https://example.com/pr/1
      number: 1
      source: observed
      target: main
      body:
        observed body

      url: https://example.com/pr/2
      number: 2
      source: child
      target: observed
      body:
        child body

        <!-- branch-stack-start -->

        -------------------------
        - main
          - https://example.com/pr/1
            - https://example.com/pr/2 :point_left:

        <sup>[Stack](https://www.git-town.com/how-to/proposal-breadcrumb.html) generated by [Git Town](https://github.com/git-town/git-town)</sup>

        <!-- branch-stack-end -->
      """
