Feature: sync the current feature branch and update proposals

  Background:
    Given a Git repo with origin
    And the origin is "git@github.com:git-town/git-town.git"
    And the branches
      | NAME    | TYPE    | PARENT | LOCATIONS     |
      | feature | feature | main   | local, origin |
      | other   | feature | main   | local, origin |
    And the commits
      | BRANCH  | LOCATION | MESSAGE               |
      | main    | local    | local main commit     |
      |         | origin   | origin main commit    |
      | feature | local    | local feature commit  |
      |         | origin   | origin feature commit |
      | other   | local    | local other commit    |
      |         | origin   | origin other commit   |
    And the proposals
      | ID | SOURCE BRANCH | TARGET BRANCH | TITLE            | BODY         | URL                      |
      | 1  | feature       | main          | feature proposal | feature body | https://example.com/pr/1 |
      | 2  | other         | main          | other proposal   | other body   | https://example.com/pr/2 |
    And Git setting "git-town.proposals-show-lineage" is "cli"
    And the current branch is "feature"
    When I run "git-town sync"

  Scenario: result
    Then Git Town runs the commands
      | BRANCH  | COMMAND                                                           |
      | feature | git fetch --prune --tags                                          |
      |         | git checkout main                                                 |
      | main    | git -c rebase.updateRefs=false rebase origin/main                 |
      |         | git push                                                          |
      |         | git checkout feature                                              |
      | feature | git merge --no-edit --ff main                                     |
      |         | git merge --no-edit --ff origin/feature                           |
      |         | git push                                                          |
      |         | Finding all proposals for feature ... main                        |
      |         | Finding proposal from feature into main ... #1 (feature proposal) |
      |         | Update body for #1 ... ok                                         |
    And these commits exist now
      | BRANCH  | LOCATION      | MESSAGE                                                    |
      | main    | local, origin | origin main commit                                         |
      |         |               | local main commit                                          |
      | feature | local, origin | local feature commit                                       |
      |         |               | Merge branch 'main' into feature                           |
      |         |               | origin feature commit                                      |
      |         |               | Merge remote-tracking branch 'origin/feature' into feature |
      | other   | local         | local other commit                                         |
      |         | origin        | origin other commit                                        |
    And the proposals are now
      """
      url: https://example.com/pr/1
      number: 1
      source: feature
      target: main
      body:
        feature body

        <!-- branch-stack-start -->

        -------------------------
        - main
          - https://example.com/pr/1 :point_left:

        <sup>[Stack](https://www.git-town.com/how-to/github-actions-breadcrumb.html) generated by [Git Town](https://github.com/git-town/git-town)</sup>

        <!-- branch-stack-end -->

      url: https://example.com/pr/2
      number: 2
      source: other
      target: main
      body:
        other body
      """

  Scenario: undo
    When I run "git-town undo"
    Then Git Town runs the commands
      | BRANCH  | COMMAND                                                                                |
      | feature | git reset --hard {{ sha 'local feature commit' }}                                      |
      |         | git push --force-with-lease origin {{ sha-in-origin 'origin feature commit' }}:feature |
    And the initial branches and lineage exist now
    And these commits exist now
      | BRANCH  | LOCATION      | MESSAGE               |
      | main    | local, origin | origin main commit    |
      |         |               | local main commit     |
      | feature | local         | local feature commit  |
      |         | origin        | origin feature commit |
      | other   | local         | local other commit    |
      |         | origin        | origin other commit   |
    And the proposals are now
      """
      url: https://example.com/pr/1
      number: 1
      source: feature
      target: main
      body:
        feature body

        <!-- branch-stack-start -->

        -------------------------
        - main
          - https://example.com/pr/1 :point_left:

        <sup>[Stack](https://www.git-town.com/how-to/github-actions-breadcrumb.html) generated by [Git Town](https://github.com/git-town/git-town)</sup>

        <!-- branch-stack-end -->

      url: https://example.com/pr/2
      number: 2
      source: other
      target: main
      body:
        other body
      """
