Feature: sync the current feature branch and update proposals

  Background:
    Given a Git repo with origin
    And the origin is "git@github.com:git-town/git-town.git"
    And the branches
      | NAME    | TYPE    | PARENT | LOCATIONS     |
      | feature | feature | main   | local, origin |
      | other   | feature | main   | local, origin |
    And the commits
      | BRANCH  | LOCATION      | MESSAGE        |
      | feature | local, origin | feature commit |
      | other   | local, origin | other commit   |
    And the proposals
      | ID | SOURCE BRANCH | TARGET BRANCH | TITLE            | BODY         | URL                      |
      | 1  | feature       | main          | feature proposal | feature body | https://example.com/pr/1 |
      | 2  | other         | main          | other proposal   | other body   | https://example.com/pr/2 |
    And Git setting "git-town.proposals-show-lineage" is "cli"
    And the current branch is "feature"
    When I run "git-town sync"

  Scenario: result
    Then Git Town runs the commands
      | BRANCH  | COMMAND                                                           |
      | feature | git fetch --prune --tags                                          |
      |         | Finding all proposals for feature ... main                        |
      |         | Finding proposal from feature into main ... #1 (feature proposal) |
      |         | Update body for #1 ... ok                                         |
      |         | Finding all proposals for other ... main                          |
      |         | Finding proposal from other into main ... #2 (other proposal)     |
      |         | Update body for #2 ... ok                                         |
    And the proposals are now
      """
      url: https://example.com/pr/1
      number: 1
      source: feature
      target: main
      body:
        feature body

        <!-- branch-stack-start -->

        -------------------------
        - main
          - https://example.com/pr/1 :point_left:

        <sup>[Stack](https://www.git-town.com/how-to/github-actions-breadcrumb.html) generated by [Git Town](https://github.com/git-town/git-town)</sup>

        <!-- branch-stack-end -->

      url: https://example.com/pr/2
      number: 2
      source: other
      target: main
      body:
        other body

        <!-- branch-stack-start -->

        -------------------------
        - main
          - https://example.com/pr/2 :point_left:

        <sup>[Stack](https://www.git-town.com/how-to/github-actions-breadcrumb.html) generated by [Git Town](https://github.com/git-town/git-town)</sup>

        <!-- branch-stack-end -->
      """

  Scenario: undo
    When I run "git-town undo"
    Then Git Town runs no commands
    And the initial branches and lineage exist now
    And the proposals are now
      """
      url: https://example.com/pr/1
      number: 1
      source: feature
      target: main
      body:
        feature body

        <!-- branch-stack-start -->

        -------------------------
        - main
          - https://example.com/pr/1 :point_left:

        <sup>[Stack](https://www.git-town.com/how-to/github-actions-breadcrumb.html) generated by [Git Town](https://github.com/git-town/git-town)</sup>

        <!-- branch-stack-end -->

      url: https://example.com/pr/2
      number: 2
      source: other
      target: main
      body:
        other body

        <!-- branch-stack-start -->

        -------------------------
        - main
          - https://example.com/pr/2 :point_left:

        <sup>[Stack](https://www.git-town.com/how-to/github-actions-breadcrumb.html) generated by [Git Town](https://github.com/git-town/git-town)</sup>

        <!-- branch-stack-end -->
      """
