#!/bin/bash

if [ `env | grep "TRAVIS=true" | wc -l` == 1 ]; then
  echo "I am on Travis CI!"
  on_travis_ci=true
  current_dir=`pwd`
  if [ `echo $PATH | grep -o $current_dir | wc -l` == 0 ]; then
    echo "Adding current dir to path"
    PATH=`pwd`:$PATH
  fi
else
  on_travis_ci=false
fi

start_time=`date +%s`

# The root directory of the Git Town source code
git_town_root_dir=`pwd`
source "$git_town_root_dir/helpers/terminal_helpers.sh"
source "$git_town_root_dir/helpers/bash_helpers.sh"

source "$git_town_root_dir/spec/helpers/command_line_parser.sh"
source "$git_town_root_dir/spec/helpers/repo_management.sh"
source "$git_town_root_dir/spec/helpers/config_file.sh"
source "$git_town_root_dir/spec/helpers/logging.sh"
source "$git_town_root_dir/spec/helpers/bdd.sh"
source "$git_town_root_dir/spec/helpers/expects.sh"
source "$git_town_root_dir/spec/helpers/spec_runners.sh"
source "$git_town_root_dir/spec/helpers/stubs.sh"
enter_test_repo
source "$git_town_root_dir/helpers/file_helpers.sh"
create_test_config_file
source "$git_town_root_dir/helpers/configuration.sh"
source "$git_town_root_dir/helpers/git_helpers.sh"
reset_logs
echo

# Run the specs
if [ $run_all_specs == true ]; then
  echo_intro "RUNNING ALL SPECS"
  run_all_specs
else
  echo_intro "RUNNING SPEC $spec_filename"
  run_single_spec $git_town_root_dir/$spec_filename
fi

echo
echo
echo_header "TEST SUMMARY"
cat $summary_log

### Verify the results
echo
echo
if [[ -s $failures_log ]]; then
  echo_failure "SOME SPECS HAVE FAILED!"
  echo
  exit_code=1
else
  echo_success "ALL SPECS ARE PASSING"
  echo
  exit_code=0
fi

### Clean up after the tests
reset_logs

end_time=`date +%s`
echo "Tests took `date -jr $(($end_time - $start_time)) +%M:%S`"
echo

exit $exit_code
