Feature: sync a stack and update proposals

  Background:
    Given a Git repo with origin
    And the origin is "git@github.com:git-town/git-town.git"
    And the branches
      | NAME  | TYPE    | PARENT | LOCATIONS     |
      | alpha | feature | main   | local, origin |
    And the commits
      | BRANCH | LOCATION      | MESSAGE |
      | alpha  | local, origin | alpha 1 |
    And the branches
      | NAME | TYPE    | PARENT | LOCATIONS     |
      | beta | feature | alpha  | local, origin |
    And the commits
      | BRANCH | LOCATION      | MESSAGE |
      | beta   | local, origin | beta 1  |
    And the branches
      | NAME  | TYPE    | PARENT | LOCATIONS     |
      | gamma | feature | beta   | local, origin |
    And the commits
      | BRANCH | LOCATION      | MESSAGE |
      | gamma  | local, origin | gamma 1 |
    And the branches
      | NAME  | TYPE    | PARENT | LOCATIONS     |
      | delta | feature | gamma  | local, origin |
    And the commits
      | BRANCH | LOCATION      | MESSAGE |
      | delta  | local, origin | delta 1 |
    And the proposals
      | ID | SOURCE BRANCH | TARGET BRANCH | TITLE          | BODY       | URL                      |
      | 1  | alpha         | main          | alpha proposal | alpha body | https://example.com/pr/1 |
      | 2  | beta          | alpha         | beta proposal  | beta body  | https://example.com/pr/2 |
      | 3  | gamma         | beta          | gamma proposal | gamma body | https://example.com/pr/3 |
      | 4  | delta         | gamma         | delta proposal | delta body | https://example.com/pr/4 |
    And Git setting "git-town.proposals-show-lineage" is "cli"
    And the current branch is "main"
    When I run "git-town sync --all"

  Scenario: result
    Then Git Town runs the commands
      | BRANCH | COMMAND                                                        |
      | main   | git fetch --prune --tags                                       |
      |        | git checkout alpha                                             |
      | alpha  | git checkout beta                                              |
      | beta   | git checkout gamma                                             |
      | gamma  | git checkout delta                                             |
      | delta  | git checkout main                                              |
      | main   | git push --tags                                                |
      |        | Finding all proposals for alpha ... main                       |
      |        | Finding proposal from alpha into main ... #1 (alpha proposal)  |
      |        | Finding proposal from beta into alpha ... #2 (beta proposal)   |
      |        | Finding proposal from gamma into beta ... #3 (gamma proposal)  |
      |        | Finding proposal from delta into gamma ... #4 (delta proposal) |
      |        | Update body for #1 ... ok                                      |
      |        | Finding all proposals for beta ... alpha                       |
      |        | Finding proposal from alpha into main ... #1 (alpha proposal)  |
      |        | Update body for #2 ... ok                                      |
      |        | Finding all proposals for delta ... gamma                      |
      |        | Finding proposal from beta into alpha ... #2 (beta proposal)   |
      |        | Update body for #4 ... ok                                      |
      |        | Finding all proposals for gamma ... beta                       |
      |        | Finding proposal from delta into gamma ... #4 (delta proposal) |
      |        | Update body for #3 ... ok                                      |
    And the initial branches and lineage exist now
    And the initial commits exist now
    And the proposals are now
      """
      url: https://example.com/pr/1
      number: 1
      source: alpha
      target: main
      body:
        alpha body

        <!-- branch-stack-start -->

        -------------------------
        - main
          - https://example.com/pr/1 :point_left:
            - https://example.com/pr/2
              - https://example.com/pr/3
                - https://example.com/pr/4

        <sup>[Stack](https://www.git-town.com/how-to/github-actions-breadcrumb.html) generated by [Git Town](https://github.com/git-town/git-town)</sup>

        <!-- branch-stack-end -->

      url: https://example.com/pr/2
      number: 2
      source: beta
      target: alpha
      body:
        beta body

        <!-- branch-stack-start -->

        -------------------------
        - main
          - https://example.com/pr/1
            - https://example.com/pr/2 :point_left:
              - https://example.com/pr/3
                - https://example.com/pr/4

        <sup>[Stack](https://www.git-town.com/how-to/github-actions-breadcrumb.html) generated by [Git Town](https://github.com/git-town/git-town)</sup>

        <!-- branch-stack-end -->

      url: https://example.com/pr/3
      number: 3
      source: gamma
      target: beta
      body:
        gamma body

        <!-- branch-stack-start -->

        -------------------------
        - main
          - https://example.com/pr/1
            - https://example.com/pr/2
              - https://example.com/pr/3 :point_left:
                - https://example.com/pr/4

        <sup>[Stack](https://www.git-town.com/how-to/github-actions-breadcrumb.html) generated by [Git Town](https://github.com/git-town/git-town)</sup>

        <!-- branch-stack-end -->

      url: https://example.com/pr/4
      number: 4
      source: delta
      target: gamma
      body:
        delta body

        <!-- branch-stack-start -->

        -------------------------
        - main
          - https://example.com/pr/1
            - https://example.com/pr/2
              - https://example.com/pr/3
                - https://example.com/pr/4 :point_left:

        <sup>[Stack](https://www.git-town.com/how-to/github-actions-breadcrumb.html) generated by [Git Town](https://github.com/git-town/git-town)</sup>

        <!-- branch-stack-end -->
      """
