.TH "GIT-HACK" "1" "04/02/2015" "Git Town 0\&.6\&.0" "Git Town Manual"

.SH "NAME"
git hack \- create a new feature branch


.SH "SYNOPSIS"
\fIgit hack\fR <branchname> [parent branch name]
.br
\fIgit hack\fR (--abort | --continue)


.SH "DESCRIPTION"
Syncs the given parent branch,
.br
forks a new feature branch off it,
.br
and brings over all uncommitted changes to the new feature branch.


.SH "OPTIONS"
.IP "<branchname>" 4
The name of the branch to create.

.IP "[parent branch name]" 4
If provided, cuts the new branch off the given existing feature branch.
.br
Providing '.' here uses the current branch as the parent branch.
.br
If omitted, uses the main branch as the parent.

.IP "--abort" 4
Cancel the operation and reset the workspace to a consistent state.

.IP "--continue" 4
Continue the operation after resolving conflicts.
