.TH "GIT-TOWN-PRUNE-BRANCHES" "1" "12/26/2016" "Git Town 2\&.1\&.0" "Git Town Manual"

.SH "NAME"
git-town-prune-branches \- delete merged branches


.SH "SYNOPSIS"
\fIgit town-prune-branches\fR


.SH "DESCRIPTION"
Deletes branches whose tracking branch no longer exists
from the local repository.
.br
This usually means the branch was shipped or killed on another machine.
