.TH "GIT-TOWN" "1" "06/24/2016" "Git Town 0\&.10\&.1" "Git Town Manual"

.SH "SYNOPSIS"
\fIgit town\fR config [--reset | --setup]
.br
\fIgit town\fR hack-push-flag [(true | false)]
.br
\fIgit town\fR help
.br
\fIgit town\fR install-fish-autocompletion
.br
\fIgit town\fR main-branch [<branch_name>]
.br
\fIgit town\fR perennial-branches [(--add | --remove) <branch_name>]
.br
\fIgit town\fR pull-branch-strategy [(rebase | merge)]
.br
\fIgit town\fR version


.SH "DESCRIPTION"
Git Town is a collection of additional Git commands that help implement higher-level Git workflows like GitHub Flow.

For more information and full documentation, please visit: \fihttps://github.com/Originate/git-town\fR


.SH "GIT COMMANDS"
\fBgit hack\fR              Cut a new feature branch off the main branch
.br
\fBgit kill\fR              Remove an obsolete feature branch
.br
\fBgit new-pull-request\fR  Create a new pull request
.br
\fBgit prune-branches\fR    Delete merged branches
.br
\fBgit rename-branch\fR     Rename a branch both locally and remotely
.br
\fBgit repo\fR              View the repository homepage
.br
\fBgit ship\fR              Deliver a completed feature branch
.br
\fBgit sync\fR              Update the current branch with all relevant changes

All commands listed here support the '--help' flag.


.SH "CONFIGURATION COMMANDS"
Git Town will automatically prompt you for the main and perennial branches
of your current repository if they haven't been set.

You may also manually view and modify the configurations:

.IP "git town config" 4
Displays your current Git Town configuration

.IP "git town config --reset" 4
Cleanly remove all Git Town configuration from the current repository

.IP "git town config --setup" 4
Run the Git Town configuration wizard

.IP "git town install-fish-autocompletion" 4
Installs the autocompletion definition for Fish shell

.IP "git town hack-push-flag <boolean>" 4
Set your git-hack push flag
.br
Valid strategy values: 'true' (default) and 'false'

.IP "git town main-branch" 4
Displays your main branch

.IP "git town main-branch <branch_name>" 4
Set your main branch to <branch_name>

.IP "git town perennial-branches" 4
Displays your perennial branches

.IP "git town perennial-branches --add <branch_name>" 4
Add a new perennial branch

.IP "git town perennial-branches --remove <branch_name>" 4
Remove branch from perennial branches

.IP "git town pull-branch-strategy" 4
Displays your pull branch strategy

.IP "git town pull-branch-strategy <strategy>" 4
Set your pull branch strategy as <strategy>
.br
Valid strategy values: 'rebase' (default) and 'merge'
