.TH "GIT-TOWN-KILL" "1" "12/26/2016" "Git Town 2\&.1\&.0" "Git Town Manual"

.SH "NAME"
git town-kill \- remove an obsolete feature branch


.SH "SYNOPSIS"
\fIgit town-kill\fR [<branch_name>]
.br
\fIgit town-kill\fR --undo


.SH "DESCRIPTION"
Deletes the current branch, or <branch_name> if given,
from the local and remote repositories.
.br
Does not delete perennial branches nor the main branch.


.SH "OPTIONS"
.IP "<branch_name>" 4
The name of the branch to remove.
.br
If not provided, removes the current branch.

.IP "--undo" 4
Undo the previous "git town-kill" operation
