.TH "GIT-HACK" "1" "09/02/2015" "Git Town 0\&.7\&.3" "Git Town Manual"

.SH "NAME"
git hack \- create a new feature branch


.SH "SYNOPSIS"
\fIgit hack\fR <branch_name> [<parent_branch_name>]
.br
\fIgit hack\fR (--abort | --continue)


.SH "DESCRIPTION"
Syncs the given parent branch (default: main branch),
.br
forks a new feature branch with the given name off it,
.br
brings over all uncommitted changes to the new feature branch,
.br
and pushes everything to the remote repository.


.SH "OPTIONS"
.IP "<branch_name>" 4
The name of the branch to create.

.IP "<parent_branch_name>" 4
If provided, cuts the new branch off the given existing feature branch.
.br
Providing '.' here uses the current branch as the parent branch.
.br
If omitted, uses the main branch as the parent.

.IP "--abort" 4
Cancel the operation and reset the workspace to a consistent state.

.IP "--continue" 4
Continue the operation after resolving conflicts.
