.TH "GIT-NEW-PULL-REQUEST" "1" "04/02/2015" "Git Town 0\&.6\&.0" "Git Town Manual"

.SH "NAME"
git-new-pull-request \- create a new pull request

.SH "SYNOPSIS"
\fIgit new-pull-request\fR

.SH "DESCRIPTION"
Opens a browser to the "new pull request" page for the current branch on the code hosting platform.
.br
Supported only for repositories hosted on GitHub and Bitbucket.
