.TH "GIT-TOWN-NEW-PULL-REQUEST" "1" "03/27/2017" "Git Town 3\&.1\&.0" "Git Town Manual"

.SH "NAME"
git-town-new-pull-request \- create a new pull request


.SH "SYNOPSIS"
\fIgit town-new-pull-request\fR


.SH "DESCRIPTION"
Syncs the current branch
and opens a browser window to the new pull request page of your repository.
.PP
The form is pre-populated for the current branch
so that the pull request only shows the changes made
against the immediate parent branch.
.PP
Supported only for repositories hosted on GitHub and Bitbucket.
When using hosted versions of GitHub or Bitbucket,
make sure that your SSH identity contains the phrase "github" or "bitbucket",
so that Git Town can guess which hosting service you use.
Example: your SSH identity should be something like
"git@github-as-account1:Originate/git-town.git"
