.TH "GIT-EXTRACT" "1" "10/21/2014" "Git Town 0\&.3\&.0" "Git Town Manual"

.SH NAME
git extract \- copies selected commits from the current feature branch
into their own feature branch

.SH SYNOPSIS
\fIgit extract\fR <branchname> [<commit>...]

.SH DESCRIPTION
Creates the given feature branch,
and cherry-picks the commits to extract into it.
.br

.br
If not given a commit SHA, prompts the user for the commits to extract.

.SH OPTIONS
.IP "--abort" 9
Aborts a failed
.B git-extract
and resets the workspace back into a consistent state.

