.TH "GIT-EXTRACT" "1" "01/09/2015" "Git Town 0\&.5\&.0" "Git Town Manual"

.SH "NAME"
git extract \- copy selected commits from the current branch into their own branch

.SH "SYNOPSIS"
\fIgit extract\fR <branchname> [<commit>...]
.br
\fIgit extract\fR --abort
.br
\fIgit extract\fR --continue

.SH "DESCRIPTION"
If no commits are provided, prompts the user to select from a list of commits unique to the current branch.
.PP
* sync the main branch
.br
* create a feature branch off it
.br
* cherry pick commits

.SH "OPTIONS"
.IP "<branchname>" 4
The name of the branch to create.

.IP "<commit>" 4
SHA to be cherry-picked into the new branch.

.IP "--abort" 4
Cancel the operation and reset the workspace to a consistent state.

.IP "--continue" 4
Continue the operation after resolving conflicts.
