.TH "GIT-TOWN" "1" "10/21/2014" "Git Town 0\&.3\&.0" "Git Town Manual"

.SH "DESCRIPTION"
Git Town is a collection of additional Git commands that help implement
higher-level Git workflows like GitHub flow:
.br
(\fIhttp://guides.github.com/introduction/flow/index.html\fR)

For more information, please visit
.br
\fihttps://github.com/Originate/git-town\fR

.SH COMMANDS
Git Town provides the following commands.
.br
.IP "\fBgit hack\fR" 20
Create a new feature branch
.IP "\fBgit sync\fR" 20
Synchronize the current branch with the rest of the world
.IP "\fBgit ship\fR" 20
Merge a completed feature branch into the main development branch
.IP "\fBgit sync-fork\fR" 20
Pull upstream updates into a forked repository
.IP "\fBgit prune-branches\fR" 20
Remove all obsolete feature branches
.IP "\fBgit extract\fR" 20
Copy selected commits into their own feature branch

