.TH "GIT-EXTRACT" "1" "10/21/2014" "Git Town 0\&.3\&.0" "Git Town Manual"

.SH NAME
git hack \- cut a new feature branch off the main branch.

.SH SYNOPSIS
\fIgit hack\fR <branchname>

.SH DESCRIPTION
Pulls updates for the main branch and creates a new feature branch with the
given name off it.
.br
.br
Brings over all uncommitted changes.

.SH OPTIONS
.IP "--abort"
Aborts a failed
.B git-hack
and resets the workspace to how it was before running this command

