.TH "GIT-SHIP" "1" "08/28/2015" "Git Town 0\&.7\&.2" "Git Town Manual"

.SH "NAME"
git ship \- deliver a completed feature branch


.SH "SYNOPSIS"
\fIgit ship\fR [<branch_name>] [<commit_options>]
.br
\fIgit ship\fR (--abort | --continue)


.SH "DESCRIPTION"
Squash merges the current branch, or <branch_name> if given,
into the main branch, leading to linear history on the main branch.
.PP
* syncs the main branch
.br
* pulls remote updates for <branch_name>
.br
* merges the main branch into <branch_name>
.br
* squash-merges <branch_name> into the main branch
.br
* pushes the main branch to the remote repository
.br
* deletes <branch_name> from the local and remote repositories

Only shipping of direct children of the main branch is allowed.
.br
To ship a nested child branch, all ancestor branches have to be shipped or killed.


.SH "OPTIONS"
.IP "<branch_name>" 4
The branch to ship.
.br
If not provided, uses the current branch.

.IP "<commit_options>" 4
Options to pass to 'git commit' when commiting the squash merge.

.IP "--abort" 4
Cancel the operation and reset the workspace to a consistent state.

.IP "--continue" 4
Continue the operation after resolving conflicts.
