.TH "GIT-TOWN-REPO" "1" "03/27/2017" "Git Town 3\&.1\&.0" "Git Town Manual"

.SH "NAME"
git-town-repo \- view the repository homepage


.SH "SYNOPSIS"
\fIgit town-repo\fR


.SH "DESCRIPTION"
Opens a browser to the repository homepage.
.PP
Supported only for repositories hosted on GitHub and Bitbucket.
When using hosted versions of GitHub or Bitbucket,
make sure that your SSH identity contains the phrase "github" or "bitbucket",
so that Git Town can guess which hosting service you use.
Example: your SSH identity should be something like
"git@github-as-account1:Originate/git-town.git"
