.TH "GIT-TOWN-HACK" "1" "02/07/2016" "Git Town 3\&.0\&.0" "Git Town Manual"

.SH "NAME"
git town-hack \- create a new feature branch off the main development branch


.SH "SYNOPSIS"
\fIgit town-hack\fR <branch_name>
.br
\fIgit town-hack\fR (--abort | --continue)


.SH "DESCRIPTION"

.PP
Syncs the main branch,
.br
forks a new feature branch with the given name off it,
.br
pushes the new feature branch to the remote repository,
.br
and brings over all uncommitted changes to the new feature branch.

.PP
Additionally, when there is a remote upstream,
.br
the main branch is synced with its upstream counterpart.
.br
This can be disabled by toggling the "hack-push-flag" configuration:
.br
$ git town hack-push-flag false


.SH "OPTIONS"
.IP "<branch_name>" 4
The name of the branch to create.

.IP "--abort" 4
Cancel the operation and reset the workspace to a consistent state.

.IP "--continue" 4
Continue the operation after resolving conflicts.
