.TH "GIT-KILL" "1" "10/21/2014" "Git Town 0\&.3\&.0" "Git Town Manual"

.SH "NAME"
git kill \- delete an obsolete feature branch

.SH "SYNOPSIS"
\fIgit kill [<branchname>]\fR
\fIgit kill\fR --undo

.SH "DESCRIPTION"
Deletes a feature branch from the local and remote repositories.

Removes the branch with the given name, or the current branch if none is
provided as a parameter.

.br
Does not delete non-feature branches nor the main branch.


.SH OPTIONS
.IP "<branchname>" 4
The name of the branch to remove.
If not provided, removes the current branch.

.IP "--undo" 4
Restores the last deleted Git branch.
