.TH "GIT-NEW-PULL-REQUEST" "1" "01/21/2016" "Git Town 0\&.10\&.0" "Git Town Manual"

.SH "NAME"
git-new-pull-request \- create a new pull request


.SH "SYNOPSIS"
\fIgit new-pull-request\fR


.SH "DESCRIPTION"
Syncs the current branch
and opens a browser window to the new pull request page of your repository.
.PP
The form is pre-populated for the current branch
so that the pull request only shows the changes made
against the immediate parent branch.
.PP
Supported only for repositories hosted on GitHub and Bitbucket.
