.TH "GIT-SYNC-FORK" "1" "01/08/2015" "Git Town 0\&.5\&.0" "Git Town Manual"

.SH "NAME"
git sync-fork \- pull upstream updates into a forked repository

.SH "SYNOPSIS"
\fIgit sync-fork\fR
.br
\fIgit sync-fork\fR --abort
.br
\fIgit sync-fork\fR --continue

.SH "DESCRIPTION"
Pulls updates from the upstream main branch into the main branch of this repository.

.SH "OPTIONS"
.IP "--abort" 4
Cancel the operation and reset the workspace to a consistent state.

.IP "--continue" 4
Continue the operation after resolving conflicts.
