.TH "GIT-SYNC" "1" "01/08/2014" "Git Town 0\&.5\&.0" "Git Town Manual"

.SH "NAME"
git sync \- update the current branch with all relevant changes

.SH "SYNOPSIS"
\fIgit sync\fR
.br
\fIgit sync\fR --abort
.br
\fIgit sync\fR --continue

.SH "DESCRIPTION"
Synchronizes the current branch with the rest of the world.

.PP
When run on a feature branch
.br
* syncs the main branch
.br
* pulls updates for the current branch
.br
* merges the main branch into the current branch
.br
* pushes the current branch

.PP
When run on the main branch or a non-feature branch
.br
* pulls and pushes updates for the current branch
.br
* pushes tags

.SH "OPTIONS"
.IP "--abort" 4
Cancel the operation and reset the workspace to a consistent state.

.IP "--continue" 4
Continue the operation after resolving conflicts.
