.TH "GIT-HACK" "1" "01/09/2015" "Git Town 0\&.5\&.0" "Git Town Manual"

.SH "NAME"
git hack \- cut a new feature branch off the main branch

.SH "SYNOPSIS"
\fIgit hack\fR <branchname>
.br
\fIgit hack\fR (--abort | --continue)

.SH "DESCRIPTION"
Sync the main branch and create a new feature branch with the given name.
.br
Brings over all uncommitted changes.

.SH "OPTIONS"
.IP "<branchname>" 4
The name of the branch to create.

.IP "--abort" 4
Cancel the operation and reset the workspace to a consistent state.

.IP "--continue" 4
Continue the operation after resolving conflicts.
