.TH "GIT-KILL" "1" "12/02/2014" "Git Town 0\&.4\&.1" "Git Town Manual"

.SH "NAME"
git kill \- remove an obsolete feature branch


.SH "SYNOPSIS"
\fIgit kill [<branchname>]\fR
\fIgit kill\fR --undo


.SH "DESCRIPTION"
Deletes the current branch, or <branchname> if given,
from the local and remote repositories.

.br
Does not delete non-feature branches nor the main branch.


.SH OPTIONS

.IP "<branchname>" 4
The name of the branch to remove.
If not provided, removes the current branch.

.IP "--undo" 4
Undo the previous "git kill" operation
