.TH "GIT-PRUNE-BRANCHES" "1" "11/13/2014" "Git Town 0\&.4\&.0" "Git Town Manual"

.SH "NAME"
git-pr \- open the browser for a new pull request

.SH "SYNOPSIS"
\fIgit pr\fR

.SH "DESCRIPTION"
Opens the browser to the form for a new pull request for the current branch.
.br
Supported only for repositories hosted on Github and Bitbucket.
