.TH "GIT-PRUNE-BRANCHES" "1" "08/05/2016" "Git Town 1\&.0\&.0" "Git Town Manual"

.SH "NAME"
git-prune-branches \- delete merged branches


.SH "SYNOPSIS"
\fIgit prune-branches\fR


.SH "DESCRIPTION"
Deletes branches whose tracking branch no longer exists
from the local repository.
.br
This usually means the branch was shipped or killed on another machine.
