#!/usr/bin/env bash
source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/helpers/helpers.sh"


function ensure_has_target_branch {
  if [ -z "$target_branch_name" ]; then
    echo_error_header
    echo_error "No branch name provided."
    exit_with_error newline
  fi
}


function preconditions {
  target_branch_name=$1
  parent_branch_name=$2

  ensure_has_target_branch
  if [ -z "$parent_branch_name" ]; then
    parent_branch_name=$MAIN_BRANCH_NAME
  fi

  if [ "$(has_remote_url)" = true ]; then
    fetch
  fi

  ensure_does_not_have_branch "$target_branch_name"
}


function steps {
  echo_if_true "stash_open_changes" "$INITIAL_OPEN_CHANGES"

  # sync the parent branch
  parent_branches "$parent_branch_name" | while read branch_name; do
    sync_branch_steps "$branch_name"
  done
  sync_branch_steps "$parent_branch_name"

  echo "create_and_checkout_feature_branch $target_branch_name $parent_branch_name"

  echo_if_true "restore_open_changes" "$INITIAL_OPEN_CHANGES"
}


run "$@"
