#!/bin/bash
source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/helpers/helpers.sh"


function preconditions {
  fetch
}


function skip_message {
  echo "To skip the sync of the '$(get_current_branch_name)' branch"
}


function skippable {
  if [ "$(get_current_branch_name)" != "$main_branch_name" ]; then
    echo true
  else
    echo false
  fi
}


function steps {
  if [ "$initial_open_changes" = true ]; then
    echo "stash_open_changes"
  fi

  echo "checkout_main_branch"
  echo "rebase_tracking_branch"
  echo "push"

  local_branches_without_main | while read branch_name; do
    echo "checkout $branch_name"

    if [ "$(is_feature_branch "$branch_name")" = true ]; then
      echo "merge_tracking_branch"
      echo "merge $main_branch_name"
    else
      echo "rebase_tracking_branch"
    fi

    echo "push"
  done

  echo "checkout $initial_branch_name"

  if [ "$initial_open_changes" = true ]; then
    echo "restore_open_changes"
  fi
}


run "$@"
