#!/usr/bin/env bash
source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/helpers/helpers.sh" --bypass-automatic-configuration --bypass-environment-checks


function show_help {
  man git-town
}


function show_version {
  echo "Git Town 0.5.0"
}


if [ "$1" == "config" ]; then
  ensure_git_repository
  shift
  show_or_reset_config "$@"
elif [ "$1" == "main-branch" ]; then
  ensure_git_repository
  shift
  show_or_update_main_branch "$@"
elif [ "$1" == "non-feature-branches" ]; then
  ensure_git_repository
  shift
  show_or_update_non_feature_branches "$@"
elif [ "$1" == "version" ]; then
  show_version
elif [ -z "$1" ] || [ "$1" == "help" ]; then
  show_help
elif [ -n "$1" ]; then
  echo_inline_error "unsupported subcommand '$1'"
  echo_inline_usage "git town"
  echo_inline_usage_or "git town config"
  echo_inline_usage_or "git town help"
  echo_inline_usage_or "git town main-branch [<branchname>]"
  echo_inline_usage_or "git town non-feature-branches [(--add | --remove) <branchname>]"
  echo_inline_usage_or "git town version"
fi
