#!/usr/bin/env bash
source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/helpers/helpers.sh"


function ensure_has_target_branch {
  if [ -z "$target_branch_name" ]; then
    echo_error_header
    echo_error "No branch name provided."
    exit_with_error
  fi
}


function preconditions {
  target_branch_name=$1
  ensure_has_target_branch
  fetch
  ensure_does_not_have_branch "$target_branch_name"
}


function steps {
  if [ "$initial_open_changes" = true ]; then
    echo "stash_open_changes"
  fi

  echo "checkout_main_branch"
  echo "rebase_tracking_branch"
  echo "push"
  echo "create_and_checkout_feature_branch '$target_branch_name'"

  if [ "$initial_open_changes" = true ]; then
    echo "restore_open_changes"
  fi
}


run "$@"
