#!/usr/bin/env bash
source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/helpers/helpers.sh"


function branch_to_kill {
  if [ -z "$1" ]; then
    echo "$INITIAL_BRANCH_NAME"
  else
    echo "$1"
  fi
}


function preconditions {
  target_branch=$(branch_to_kill "$@")
  parent_branch_name=$(parent_branch "$target_branch")

  ensure_is_feature_branch "$target_branch" "You can only kill feature branches."

  if [ "$HAS_REMOTE" = true ]; then
      fetch
  fi

  if [ "$target_branch" != "$INITIAL_BRANCH_NAME" ]; then
    ensure_has_branch "$target_branch"
  fi
}


function steps {
  if [ "$target_branch" = "$INITIAL_BRANCH_NAME" ]; then
    echo_if_true "commit_open_changes" "$INITIAL_OPEN_CHANGES"
    echo "checkout $parent_branch_name"
  fi

  if [ "$(has_tracking_branch "$target_branch")" = true ]; then
    echo "delete_remote_branch $target_branch"
  fi

  echo "delete_local_branch $target_branch force"

  # update branch hierarchy information
  echo_update_child_branches "$target_branch" "$parent_branch_name"
  echo "delete_parent_entry $target_branch"
  echo "delete_all_ancestor_entries"
}


run "$@"
