#!/usr/bin/env bash
source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/helpers/helpers.sh"


function preconditions {
  activate_driver_family 'code_hosting'
}


function steps {
  echo "show_repo $(remote_repository_name)"
}


run "$@"
