#!/usr/bin/env bash
source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/helpers/helpers.sh"


function ensure_has_shas {
  if [ -z "$SHAs" ]; then
    echo_error_header
    echo_error "Nothing selected, aborting extract."
    exit_with_error newline
  fi
}


function ensure_has_target_branch {
  if [ -z "$target_branch_name" ]; then
    echo_error_header
    echo_error "No branch name provided."
    exit_with_error newline
  fi
}


function get_shas {
  SHAs="$*"

  if [ -z "$SHAs" ]; then
    ensure_has_extractable_commits
    ensure_tool_installed 'dialog'
    local file=$(temp_filename)

    git log --oneline --reverse "$MAIN_BRANCH_NAME..$INITIAL_BRANCH_NAME"     | # Get a list of all commits in the feature branch in reverse order
      awk '{ print $1 " " "\047" substr($0, index($0,$2)) "\047" " " "off" }' | # Put quotes around commit message, append ' off' to each line (required by dialog)
      xargs dialog --title "Please select all commits to be extracted from the '$INITIAL_BRANCH_NAME' branch into the '$target_branch_name' branch" --ok-label "Extract" --cancel-label "Abort" --checklist "" 0 0 0  2> "$file"  # Ask the user for commits
    clear

    SHAs=$(cat "$file")
    rm "$file"
  fi
}


function preconditions {
  target_branch_name=$1
  ensure_has_target_branch

  if [ "$HAS_REMOTE" = true ]; then
    fetch
  fi

  ensure_does_not_have_branch "$target_branch_name"
  shift
  get_shas "$*"
  ensure_has_shas
}


function should_stash_open_changes {
  echo true
}


function steps {
  echo "checkout_main_branch"
  echo "rebase_tracking_branch"
  echo_if_true "push_branch $MAIN_BRANCH_NAME" "$HAS_REMOTE"
  echo "create_and_checkout_feature_branch '$target_branch_name'"
  echo "cherry_pick '$SHAs'"
  echo_if_true "push_branch $target_branch_name" "$HAS_REMOTE"
}


run "$@"
