#!/usr/bin/env bash
source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/helpers/helpers.sh"


function preconditions {
  activate_driver_family 'code_hosting'
}


function steps {
  echo "create_pull_request $(remote_repository_name) $INITIAL_BRANCH_NAME"
}


run "$@"
