#!/usr/bin/env bash
source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/helpers/helpers.sh"


function ensure_has_upstream {
  if [ "$(git remote -v | grep -c 'upstream')" == 0 ]; then
    echo_error_header
    echo_error "Please add a remote 'upstream'"
    exit_with_error newline
  fi
}


function preconditions {
  ensure_has_upstream
}


function should_stash_open_changes {
  echo true
}


function steps {
  echo "checkout_main_branch"
  echo "fetch_upstream"
  echo "rebase upstream/$MAIN_BRANCH_NAME"
  echo "push"
  echo "checkout $INITIAL_BRANCH_NAME"
}


run "$@"
