// Package steps defines the individual operations that the Git Town VM can execute.
// All steps implement the Step interface defined in step.go.
package opcode

import "github.com/git-town/git-town/v9/src/vm/shared"

func DetermineStep(stepType string) shared.Opcode { //nolint:ireturn
	switch stepType {
	case "AbortMerge":
		return &AbortMerge{}
	case "AbortRebase":
		return &AbortRebase{}
	case "AddToPerennialBranches":
		return &AddToPerennialBranches{}
	case "ChangeParent":
		return &ChangeParent{}
	case "Checkout":
		return &Checkout{}
	case "CheckoutIfExists":
		return &CheckoutIfExists{}
	case "CommitOpenChanges":
		return &CommitOpenChanges{}
	case "ConnectorMergeProposal":
		return &ConnectorMergeProposal{}
	case "ContinueMerge":
		return &ContinueMerge{}
	case "ContinueRebase":
		return &ContinueRebase{}
	case "CreateBranch":
		return &CreateBranch{}
	case "CreateBranchExistingParent":
		return &CreateBranchExistingParent{}
	case "CreateProposal":
		return &CreateProposal{}
	case "CreateRemoteBranch":
		return &CreateRemoteBranch{}
	case "CreateTrackingBranch":
		return &CreateTrackingBranch{}
	case "DeleteLocalBranch":
		return &DeleteLocalBranch{}
	case "DeleteParentBranch":
		return &DeleteParentBranch{}
	case "DeleteRemoteBranch":
		return &DeleteRemoteBranch{}
	case "DeleteTrackingBranch":
		return &DeleteTrackingBranch{}
	case "DiscardOpenChanges":
		return &DiscardOpenChanges{}
	case "EnsureHasShippableChanges":
		return &EnsureHasShippableChanges{}
	case "FetchUpstream":
		return &FetchUpstream{}
	case "ForcePushCurrentBranch":
		return &ForcePushCurrentBranch{}
	case "Merge":
		return &Merge{}
	case "MergeParent":
		return &MergeParent{}
	case "PreserveCheckoutHistory":
		return &PreserveCheckoutHistory{}
	case "PullCurrentBranch":
		return &PullCurrentBranch{}
	case "PushCurrentBranch":
		return &PushCurrentBranch{}
	case "PushTags":
		return &PushTags{}
	case "RebaseBranch":
		return &RebaseBranch{}
	case "RebaseParent":
		return &RebaseParent{}
	case "RemoveFromPerennialBranches":
		return &RemoveFromPerennialBranches{}
	case "RemoveGlobalConfig":
		return &RemoveGlobalConfig{}
	case "RemoveLocalConfig":
		return &RemoveLocalConfig{}
	case "ResetCurrentBranchToSHA":
		return &ResetCurrentBranchToSHA{}
	case "ResetRemoteBranchToSHA":
		return &ResetRemoteBranchToSHA{}
	case "RestoreOpenChanges":
		return &RestoreOpenChanges{}
	case "RevertCommit":
		return &RevertCommit{}
	case "SetExistingParent":
		return &SetExistingParent{}
	case "SetGlobalConfig":
		return &SetGlobalConfig{}
	case "SetLocalConfig":
		return &SetLocalConfig{}
	case "SetParent":
		return &SetParent{}
	case "SetParentIfBranchExists":
		return &SetParentIfBranchExists{}
	case "SquashMerge":
		return &SquashMerge{}
	case "SkipCurrentBranch":
		return &SkipCurrentBranch{}
	case "StashOpenChanges":
		return &StashOpenChanges{}
	case "UndoLastCommit":
		return &UndoLastCommit{}
	case "UpdateProposalTarget":
		return &UpdateProposalTarget{}
	}
	return nil
}
