name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - uses: dprint/check@v2.0
    - run: vim --version
    - run: make setup-godog
    - run: make unit
    - run: make cuke
